### ISSUE TITLE
邮箱设置问题

### ISSUE THREAD

**Issue by kdaye** [sjdy521/Mojo-Webqq#102]
```
perl -MMojo::Webqq -e 'Mojo::Webqq->省略->load("PostQRcode",data=>{smtp=>"smtp.qq.com",port=>"465",from=>"@qq.com",to=>"1@qq.com",user=>"@qq.com",pass=>"******",tls=>0})->run'
```
如上。得到的error是
[error] 插件[Mojo::Webqq::Plugin::PostQRcode]邮件发送失败: Inactivity timeout
不知道为什么会这样。请问该如何正确配置？
请问使用邮箱的各位，都是用什么邮箱的？

**Comment by sjdy521** [comment]
465端口是ssl端口，需要设置```tls=>1```
默认情况下，你设置了```port=>465```，程序会自动设置```tls=>1``` 但你现在强制```tls=>0``` 就有问题了

另外，qq邮箱的smtp登录使用的并不是你的qq密码，而是你需要再网页邮箱中设置生成一个动态授权码，这点还请注意
