### ISSUE TITLE
关于代理&Api

### ISSUE THREAD

**Issue by liangchenhe55** [sjdy521/Mojo-Webqq#107]
首先非常感谢开源如此棒的项目并坚持维护。
由于腾讯限制，虽然项目本身支持多QQ登陆但容易被封。能否实现每个client配置一个代理，这样应该可以尽量减少风险。
PS：不晓得是否可以整理下协议的api，这样我们可以自己做其他语言的实现。
再次感谢。

**Comment by sjdy521** [comment]
感谢支持
配置代理服务器目前支持linux标准方式：采用环境变量设置http请求代理，参考： http://blog.csdn.net/guo_ang/article/details/17448135

协议的文档，因为其他项目都有整理了很多，所以我也就没有整理了，可以参考：
http://www.scienjus.com/webqq-analysis-1/

**Comment by liangchenhe55** [comment]
恩我看了Linux的代理设置。但是这个不能很好地解决被封，因为腾讯还是可以发现一个ip同时登了多个webqq。
如果每个client设置一个代理，效果就不同了。

**Comment by sjdy521** [comment]
每个客户端启动的时候单独设置代理服务器就可以了 比如
env http_proxy=xxx perl xxx.pl
