### ISSUE TITLE
将消息标为已读状态

### ISSUE THREAD

**Issue by GongJianwei** [sjdy521/Mojo-Webqq#109]
请问本项目是否能实现回复消息后将消息未读的状态清除（也就是标为已读）？

**Comment by sjdy521** [comment]
基于微信网页版，功能范围也都局限在网页版范围内，没怎么注意到网页上回复消息之后手机端是否回被标记为已读，理论上有这种可能性

**Comment by GongJianwei** [comment]
@sjdy521 我知道了，但我现在回复的是 QQ 项目没错吧……顺便一提，微信应该是自带实现的，因为当网页登录后微信自动处理为不提醒消息

**Comment by sjdy521** [comment]
sorry…看错了
QQ项目道理也是一样的 可以亲自测试下
