### ISSUE TITLE
2.1.1 版本无法获取消息

### ISSUE THREAD

**Issue by kotomei** [sjdy521/Mojo-Webqq#110]
服务端无报错信息，但无法获取到消息

**Comment by sjdy521** [comment]
确认下你的插件参数设置是否正确

**Comment by kotomei** [comment]
插件参数配置无问题
另：今天早上至少有 5 人报告有此问题

sjdy521 <notifications@github.com>于2017年5月1日周一 10:03写道：

**Comment by sjdy521** [comment]
早上也看到其他类似项目收到类似issue 看来是官方做了什么改动 大家集体报障了 我会持续关注下

**Comment by kotomei** [comment]
好的 静候佳音

sjdy521 <notifications@github.com>于2017年5月1日周一 10:24写道：

**Comment by sjdy521** [comment]
据说已经恢复

**Comment by byYufeng** [comment]
没有啊 我刚提了个issue 截止到现在位置也是这样 没有用任何插件 几次失败之后就掉线（如果中间收到新信息就没事） 微信正常

**Comment by bollwarm** [comment]
你升级下版本
