### ISSUE TITLE
get_group_info 无法获取到 join_time 和 last_speak_time

### ISSUE THREAD

**Issue by yw80** [sjdy521/Mojo-Webqq#116]
根据文档 API.md 的描述，/openqq/get_group_info 返回的信息有：
[#数组
    {#第1个群
……
        "member": [
            {
                "qage": "16",
                "name": "xxx",
                **"join_time": "0",**
……
                **"last_speak_time": "1453449884",**
……

但是实际调用的时候，并没有在 member 中找到 join_time 和 last_speak_time 这两个变量。是腾讯修改了接口？还是文档没有更新呢？

还有其他 API 可以获取群成员的加群时间和最后发言时间吗？这两个时间对于群管理来说，非常重要。

**Comment by yw80** [comment]
我又测试了下，好像这个 API 不稳定，有两个群成员的 join_time 和 last_speak_time 获取到了，大部分群都没有获取到。返回的列表中，只有位于中间部分的两个群获取到了这两项信息。

**Comment by sjdy521** [comment]
因为腾讯的限制，原有的一些获取群信息的api接口已经不可用了，更换了一个新的api接口，不是很好用
偶尔会导致无法获取到你说的这些群信息

**Comment by yw80** [comment]
@sjdy521 我不懂 perl，不过有两个建议，你看下是否有参考价值：
1. 为 get_group_info 加一个参数吧，可以写群号。如果不写群号，就按照现在的逻辑；如果写了群号，就只刷新指定群的用户信息。
2. 在 QQ 软件中，打开某个群的成员窗口，有一个“高级管理”链接，点击后会跳转到 QQ 群管理页面，里面包含丰富的群信息，我觉得可以利用一下。虽然有点脱离了 web qq 的范畴。

**Comment by sjdy521** [comment]
关于第一点其实已经有另外一个接口了 /openqq/search_group 可以按照群对象的任意属性来搜索指定的群 比如 /openqq/search_group?uid=xxxxx

关于第二点 其实项目已开始就有使用qun.qq.com的群管理功能来获取群号，群禁言等丰富功能
