### ISSUE TITLE
检测到该账号有其他运行中的客户端(pid:5)该怎么做

### ISSUE THREAD

**Issue by byYufeng** [sjdy521/Mojo-Webqq#117]
是用docker -it ...的方式的起镜像。不知怎么就起不来了

**Comment by huaxinchan** [comment]
rm /tmp/mojo*

**Comment by byYufeng** [comment]
只删掉 /tmp/mojo_webqq_pid_default.pid就好了 我只顾折腾container内部了 怎么没想到这层去
 哈哈  太感谢了
