### ISSUE TITLE
KnowledgeBase加载成功，但不起作用

### ISSUE THREAD

**Issue by goodtogood** [sjdy521/Mojo-Webqq#119]
同时也发现 GroupManage 的 消息 图片  关键词频率限制也是不起作用的 只有新加入成员消息可用

Perl executable: D:\AppRoot\Mojo-Strawberry\perl\bin\perl.e
Perl version   : 5.24.0 / MSWin32-x86-multi-thread-64int
当前正在使用 Mojo-Webqq v2.1.1

> $client->load("KnowledgeBase",data=>{
>     allow_group => [3698875],  #可选，允许插件的群，可以是群名称或群号码
>     # ban_group   => ["私人群",123456], #可选，禁用该插件的群，可以是群名称或群号码
>     file => $tmpdir_dir.'KnowledgeBase.txt', #数据库保存路径，纯文本形式，可以编辑
>     learn_command  => 'learn',     #可选，自定义学习指令关键字
>     delete_command =>'del',      #可选，自定义删除指令关键字
>     learn_operator => [76292009,3797651], #允许学习权限的操作人qq号
>     delete_operator => [76292009,3797651], #允许删除权限的操作人qq号
>     mode => 'fuzzy', # fuzzy|regex|exact 分别表示模糊|正则|精确, 默认模糊
>     check_time => 10, #默认10秒检查一次文件变更
>     show_keyword => 1, #消息是否包含触发关键字信息，默认为0
> });
> 

日志级别用debug,可以看到加载成功，

> [17/05/11 11:19:27] [info] 当前正在使用 Mojo-Webqq v2.1.1
> [17/05/11 11:19:27] [info] 客户端加载cookie[ temp\mojo_webqq_cookie_default.dat
> ]
> Logining...
> If No Succeed Info in 5s Please Scan QRCode
> [17/05/11 11:19:27] [debug] 加载插件[ Mojo::Webqq::Plugin::ShowMsg ]
> [17/05/11 11:19:27] [debug] 加载插件[ Mojo::Webqq::Plugin::ShowQRcode ]
> [17/05/11 11:19:27] [info] 执行插件[ Mojo::Webqq::Plugin::ShowQRcode ]
> [17/05/11 11:19:27] [debug] 加载插件[ Mojo::Webqq::Plugin::KnowledgeBase ]
> [17/05/11 11:19:27] [debug] 加载插件[ Mojo::Webqq::Plugin::GroupManage ]
> [17/05/11 11:19:27] [debug] 加载插件[ Mojo::Webqq::Plugin::Openqq ]
> [17/05/11 11:19:27] [info] 执行插件[ Mojo::Webqq::Plugin::ShowMsg ]
> [17/05/11 11:19:27] [info] 执行插件[ Mojo::Webqq::Plugin::GroupManage ]
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_speek> Reset]添加成功
> ，时间设定: 00:00:00
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_speek> Reset]下一次触
> 发时间为：2017/05/12 00:00:00
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_pic> Reset]添加成功，
> 时间设定: 00:00:00
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_pic> Reset]下一次触发
> 时间为：2017/05/12 00:00:00
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_keyword> Reset]添加成
> 功，时间设定: 00:00:00
> [17/05/11 11:19:27] [debug] 计划任务[Counter <GroupManage_keyword> Reset]下一次
> 触发时间为：2017/05/12 00:00:00
> [17/05/11 11:19:27] [info] 执行插件[ Mojo::Webqq::Plugin::Openqq ]
> [17/05/11 11:19:27] [info] Listening at "http://0.0.0.0:5000"
> Server available at http://0.0.0.0:5000

**Comment by sjdy521** [comment]
以为webqq以前可以接收图片 现在完全收不到任何图片消息了 所以这部分功能也就失效了

**Comment by goodtogood** [comment]
@sjdy521 那KnowledgeBase呢 配置正常呀 奇怪！！

**Comment by sjdy521** [comment]
有可能是获取群号码失败，导致你设置在allow_group里的群号没有匹配到对应的群
建议除了群号，把群的名称也写到allow_group里
