### ISSUE TITLE
这个客户端是否支持在给QQ群发消息时@某人？

### ISSUE THREAD

**Issue by hsluoyz** [sjdy521/Mojo-Webqq#12]

**Comment by sjdy521** [comment]
只能是文本形式的 @xxx 不支持真正的艾特

**Comment by waylonwang** [comment]
通过跟踪某人@自己的content可以发现支持@艾特的消息是这种格式 content: [ [ 'font', [Object] ], '@waylon', '', ' 哈哈' ]，也就是说QQ客户端会将'@waylon 哈哈'拆分成三段，我尝试将web qq发送的消息强行拆分成'@waylon', '', ' 哈哈'进行发送，结果在接收消息的content中却变成了'@waylon', ' 哈哈'，且仍然不会产生艾特的效果，怀疑GUI及手Q中还会对拆分后的'@waylon'匹配真正的uid并通过另外的属性发送到服务端，由于web qq没有支持艾特的功能，导致web qq的消息接口没有包含此属性，因此对方无法收到真正的艾特。但是我发现酷Q机器人的回复是真正的艾特，可以研究一下究竟是如何实现的，也许还有其他接口是可以做到真正艾特的。

**Comment by sjdy521** [comment]
你指的是酷Q air还是酷Q pro？
据我所了解到的：air是基于web协议 应该做不到艾特
pro是基于手机或pc协议 所以才可以实现艾特

**Comment by waylonwang** [comment]
我是在图灵机器人的开发指南那下载的安装包，估计应该是酷Q Pro的技术框架做的，的确应该只有PC或安卓协议才能艾特

**Comment by Ray-Eldath** [comment]
要是能支持真艾特就好了
