### ISSUE TITLE
找到问题了

### ISSUE THREAD

**Issue by goodtogood** [sjdy521/Mojo-Webqq#120]
Mojo-Webqq v2.1.1

> [17/05/11 20:38:48] [warn] Mojo::Webqq::Util::from_json return undef value
> [17/05/11 20:38:43] [好友消息] 56XXXX56|其他 : 你
> [17/05/11 20:38:52] [warn] Malformed JSON: Expected string, array, object, numbe
> r, boolean or null at line 1, offset 9 at D:/AppRoot/Mojo-Strawberry/perl/site/l
> ib/Mojo/Webqq/Util.pm line 53.
> [17/05/11 20:38:52] [warn] Mojo::Webqq::Util::from_json return undef value
> [17/05/11 20:38:46] [好友消息] 56XXXX56|其他 : 好
> [17/05/11 20:38:55] [warn] Malformed JSON: Expected string, array, object, numbe
> r, boolean or null at line 1, offset 9 at D:/AppRoot/Mojo-Strawberry/perl/site/l
> ib/Mojo/Webqq/Util.pm line 53.
> [17/05/11 20:38:55] [warn] Mojo::Webqq::Util::from_json return undef value
> [17/05/11 20:38:49] [好友消息] 56XXXX56|其他 : 其它
> [17/05/11 20:38:58] [warn] Malformed JSON: Expected string, array, object, numbe
> r, boolean or null at line 1, offset 9 at D:/AppRoot/Mojo-Strawberry/perl/site/l
> ib/Mojo/Webqq/Util.pm line 53.
> [17/05/11 20:38:58] [warn] Mojo::Webqq::Util::from_json return undef value
> [17/05/11 20:38:52] [好友消息] 56XXXX56|其他 : 不行
> [17/05/11 20:39:01] [warn] Malformed JSON: Expected string, array, object, numbe
> r, boolean or null at line 1, offset 9 at D:/AppRoot/Mojo-Strawberry/perl/site/l
> ib/Mojo/Webqq/Util.pm line 53.
> [17/05/11 20:39:01] [warn] Mojo::Webqq::Util::from_json return undef value

**Comment by sjdy521** [comment]
很好奇 是啥原因
