### ISSUE TITLE
QQ群签到是失效了吗？

### ISSUE THREAD

**Issue by AndyBernie** [sjdy521/Mojo-Webqq#121]
一直提示签到失败

**Comment by sjdy521** [comment]
以前有签到成功过吗

**Comment by AndyBernie** [comment]
成功过一次

**Comment by AndyBernie** [comment]
成功过一次。后来就不行了

2017年5月18日 13:07，"sjdy521" <notifications@github.com>写道：

**Comment by sjdy521** [comment]
等我研究下 最近都没什么精力放在这个项目上

**Comment by AndyBernie** [comment]
恩，谢谢。不过我单独登陆w.qq.com发现里面没有QQ群签到的功能，是不是腾讯给取消了🙄

**Comment by sjdy521** [comment]
是偷用了PCQQ里的接口

**Comment by AndyBernie** [comment]
那可以用Android qq的签到接口吗？🤔

**Comment by AndyBernie** [comment]
pc端qq需要使用手机qq扫码才能完成签到，使用pc端qq恐怕是不行了吧
