### ISSUE TITLE
如果要退出登陆应该怎么做？

### ISSUE THREAD

**Issue by JWGavin** [sjdy521/Mojo-Webqq#122]
翻了半天也不知道怎么弄，能教一下嘛，感谢！

**Comment by bollwarm** [comment]
界面下ctrl+c就可以

**Comment by JWGavin** [comment]
不是ctrl＋c不能清理cookie，我发现了要加上keep_cookie=0

**Comment by bollwarm** [comment]
清理cookie吧cookie目录（默认/tmp）中的cookie文件删了就ok

**Comment by JWGavin** [comment]
原来在这里，灰常感谢，我一直不知道在哪。[开心]
