### ISSUE TITLE
API又出问题？

### ISSUE THREAD

**Issue by Ray-Eldath** [sjdy521/Mojo-Webqq#124]
从28日开始（或许更早），获取到的`sender-uid`就一直是`null`。上次出现这个问题是因为腾讯删API，这次还会是吗？
以及，如何解决？

以上。
Ray Eldath.

**Comment by sjdy521** [comment]
所有等sender_uid都是null还是部分sender_uid是null

**Comment by Ray-Eldath** [comment]
目前看来是所有的... ...
不管是Linux系统下还是Windows系统（好像本来就系统无关）

**Comment by sjdy521** [comment]
新版本对uid的获取进行了改善 可以更新到最新版本再观察下
