### ISSUE TITLE
我扫码扫错了。怎么切换账号

### ISSUE THREAD

**Issue by LanHao0** [sjdy521/Mojo-Webqq#125]
本来要用小号扫，然后没注意……用了大号……然而crtl+c取消后，再运行会自动登陆……跳过扫码

**Comment by pandolia** [comment]
用 qq fresh-restart ，或者 ctrl-c 退出后，用 qqbot -q "" 启动程序。

**Comment by sjdy521** [comment]
1、可以在手机上操作退出一下网页版
2、删除登录相关的cookie文件（客户端运行日志中会打印cookie文件路径）
