### ISSUE TITLE
POST接收到的群组消息，uid参数为null

### ISSUE THREAD

**Issue by SpadeLushen** [sjdy521/Mojo-Webqq#128]
通过POST方式接收群组消息，group_uid、sender_uid和receiver_uid参数均为null。
通过 /openqq/get_group_info获取的群组数据中，群成员的uid也都是null。

![insomnia](https://user-images.githubusercontent.com/7971040/26934598-636c1062-4c9c-11e7-9251-8eb9430a6a35.png)
![post](https://user-images.githubusercontent.com/7971040/26934599-638562e2-4c9c-11e7-9163-9d4fa75cd7f9.png)

**Comment by sjdy521** [comment]
请使用github最新代码再次测试看下是否还会存在上述问题

**Comment by SpadeLushen** [comment]
谢谢，已经解决了
