### ISSUE TITLE
无法正常发送二维码邮件

### ISSUE THREAD

**Issue by 853486395** [sjdy521/Mojo-Webqq#133]
提示
[error] 插件[Mojo::Webqq::Plugin::PostQRcode]邮件发送失败: Inactivity timeout
这台机器上同时部署了web  weixin。一样的发送邮件代码。可以正常发送。但web qq不行。很诡异。

**Comment by sjdy521** [comment]
发送邮件的配置是否可以分享出来看一下

**Comment by 853486395** [comment]
#发二维码到我的邮箱
$client->load("PostQRcode",data=>{
    smtp    =>  'smtp.qq.com',          #邮箱的smtp地址
    port    =>  '465',                  #smtp服务器端口，默认25
    from    =>  'abc@qq.com',    #发件人
    to      =>  '123@qq.com',     #收件人
    user    =>  'abc@qq.com',    #smtp登录帐号
    pass    =>  'xxxxxx',     #smtp登录密码
    tls     =>  1,                      #可选，是否使用SMTPS协议，默认为0                            
                                        #在没有设置的情况下，如果使用的端口为465，则该选项会自动被设置为1
});
