### ISSUE TITLE
终端内输出二维码

### ISSUE THREAD

**Issue by whenov** [sjdy521/Mojo-Webqq#136]
可使用类似[TerminalImageViewer](https://github.com/stefanhaustein/TerminalImageViewer)的工具在终端内输出二维码，可简化用户登录流程。

**Comment by sjdy521** [comment]
QQ暂时没办法实现，因为二维码图片里的信息（一个url）是动态生成的，没办法从图片里读取出信息再自己在终端上生成二维码，所以问题在于，终端生成二维码并不难，难的是如果从图片里读取原始的二维码数据（需要有一些读取二维码的库才能实现，但perl里暂时没有，你可以自己研究下其他的解决方式，理论上肯定是可行的）

**Comment by sjdy521** [comment]
可以把这段代码加到xxx.pl里（Mojo::Webqq->new之后，$client->run之前）

$client->on(input_qrcode=>sub{
    my($client,$qrcode_path) = @_;
    `/path/to/terminalimageviewer $qrcode_path` ; 调用外部的TerminalImageViewer命令，把二维码地址传递给命令，实现终端输出二维码
});
