### ISSUE TITLE
魅族推送问题

### ISSUE THREAD

**Issue by kannad** [sjdy521/Mojo-Webqq#137]
[17/07/24 03:17:24] [好友消息] Swei丶夜夜|剑三er : =。=
appId=110370messageJson={"content":"{\"isAt\":\"0\",\"type\":\"Mojo-Webqq\",\"title\":\"Swei丶夜夜\",\"message\":\"=。=\",\"msgId\":\"4124626166\",\"senderType\":\"1\"}"}pushIds=BNA4a666206797a01656041797c404f05414360630071eb034b0b4f42414baedaa04ddc7e6981  -- Non-blocking request (https://api-push.meizu.com/garcia/api/server/push/unvarnished/pushByPushId)
  -- Client >>> Server (https://api-push.meizu.com/garcia/api/server/push/unvarnished/pushByPushId)
  POST /garcia/api/server/push/unvarnished/pushByPushId HTTP/1.1
  User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062
  Content-Type: application/x-www-form-urlencoded
  Cookie: JSESSIONID=s58webog22y9xc8dvh6uq8zp
  Accept-Encoding: gzip
  Content-Length: 431
  Host: api-push.meizu.com

  appId=110370&messageJson=%7B%22content%22%3A%22%7B%5C%22isAt%5C%22%3A%5C%220%5C%22%2C%5C%22type%5C%22%3A%5C%22Mojo-Webqq%5C%22%2C%5C%22title%5C%22%3A%5C%22Swei%E4%B8%B6%E5%A4%9C%E5%A4%9C%5C%22%2C%5C%22message%5C%22%3A%5C%22%3D%E3%80%82%3D%5C%22%2C%5C%22msgId%5C%22%3A%5C%224124626166%5C%22%2C%5C%22senderType%5C%22%3A%5C%221%5C%22%7D%22%7D&pushIds=BNA4a666206797a01656041797c404f05414360630071&sign=cd2b3108eacb29b168690f78d0432e20
  -- Server >>> Client (https://api-push.meizu.com/garcia/api/server/push/unvarnished/pushByPushId)
  HTTP/1.1 200 OK
  Connection: keep-alive
  Set-Cookie: JSESSIONID=7lnx6vr37z971fa0xx5arbu1y;Path=/
  Date: Sun, 23 Jul 2017 19:17:24 GMT
  Content-Length: 75
  Content-Type: application/json; charset=UTF-8
  est: t
  Content-Language: en-US
  Server: nginx/1.11.6
  Expires: Thu, 01 Jan 1970 00:00:00 GMT

  {"code":"110053","message":"透传超过限制","redirect":"","value":""}

**Comment by kannad** [comment]
```
 more /root/gcm/gcm-qq.pl
use Mojo::Webqq;
#微信使用 use Mojo::Weixin
my $client = Mojo::Webqq->new(log_encoding=>"utf-8");
$client->load("ShowMsg");
#请根据自己所需的推送服务进行选择并删除或注释不需要的部分，填写格式请仿照 GCM 的方式填写
$client->load("FmPush",data=>{
    registration_ids=>["BNA4a666206797a01656041797c404f05414360630071"],
    allow_group=>[""],
    ban_group=>[],
    allow_discuss=>[],
    ban_discuss=>[],
    });
$client->load("Openqq",data=>{
    #如果是微信改为 Openwx
    listen => [{host=>"0.0.0.0",port=>5000}, ] ,
    #如果是推送微信的话需要保证端口不重复，并请保证所设定的端口已经在防火墙内放行，同时需要在 APP 内设定好推送服务器的
地址和端口
});
#不需要 APP 内回复功能请删除以上三行（不包括被 # 号注释掉的几行）
$client->run(); 
```

**Comment by kannad** [comment]
Android:5.1
Flyme 6.1.0.0A

**Comment by sjdy521** [comment]
看起来是魅族的推送api返回异常了，每次调用都产生这个错误？还是偶尔产生？

**Comment by sjdy521** [comment]
@heipidage 有空可以帮忙关注下这个问题

**Comment by kannad** [comment]
因为手头没有更多的魅族设备没办法进行更多测试
服务端是阿里云ECS
已经多次尝试仍是返回这个报错

**Comment by Curtion** [comment]
我也遇见了这个问题，服务器是香港的centos 7

**Comment by kotomei** [comment]
这个是魅族推送在透传上做出了限制，貌似无法解决
