### ISSUE TITLE
重复报错Use of uninitialized value in pattern match (m//)......

### ISSUE THREAD

**Issue by StarryFK** [sjdy521/Mojo-Webqq#142]
重复报错这些内容，虽然对运行没有任何明显的影响：

Use of uninitialized value in pattern match (m//) at /usr/local/share/perl/5.20.2/Mojo/Webqq/Message/Base.pm line 53.
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl/5.20.2/Mojo/Webqq/Message/Base.pm line 53.
Use of uninitialized value in pattern match (m//) at /usr/local/share/perl/5.20.2/Mojo/Webqq/Message/Base.pm line 53.

**Comment by sjdy521** [comment]
已修复
