### ISSUE TITLE
Smart QQ 现已支持账户密码登录

### ISSUE THREAD

**Issue by kotomei** [sjdy521/Mojo-Webqq#145]
是否考虑提供除扫码外的另一种直接登录的选择

**Comment by sjdy521** [comment]
测试了一下网页上的账号密码登录，关闭了手机设备锁，仍然无法正常登陆，等官方完全支持之后再跟进

**Comment by dou4cc** [comment]
是可以的，你先进入https://qzone.qq.com 用账号密码登录，再打开https://w.qq.com ，就能看见已登录列表里有刚登的账号，点一下就进去了。

**Comment by sjdy521** [comment]
@dou4cc 以前smartqq的登录cookie是无法和qzone/qmail/等登录cookie共享的
如果真如你所说，现在登录cookie也完全可以共享了，那真是很棒的消息，我近期会研究下

**Comment by xhebox** [comment]
@sjdy521 证实一下dou4cc的说法, 登陆api是相同的, cookie的确可以共享. 不过web页面的api调用换了几个参数组合之后还是显示登陆失败. 大概是因为这个动态生成的请求是给webqq专用的吧, 我是说那个app参数, qzone的参数换了后还是可以登陆的, 后端对于不同app类型的处理逻辑应该不一样, webqq那边的检测更严点. 目前已经登陆的账号的cookie里应该不包含登陆途经的信息, 不管在别的页面怎么登陆过, webqq页应该都能直接使用cookie.

希望能尽快支持一下, 一直用不惯vm/wine之类的, 手机扫码又麻烦的很.

**Comment by hssyuan** [comment]
如何账号密码登录啊

**Comment by sjdy521** [comment]
刚把账号密码登录给更新实现了，却发现qq空间的登录cookie已经不能够共享给webqq了……
so 还是得老老实实扫码登录了

**Comment by dou4cc** [comment]
@sjdy521 刚试了一下，我说的登录方法还是管用的呀！

**Comment by sjdy521** [comment]
奇怪了 我在chrome上亲自测试很多遍 不行呀…

**Comment by sjdy521** [comment]
@dou4cc 看来你说的对，我近期会实现下账号密码的登录方式

**Comment by sjdy521** [comment]
账号密码的登录方式已经开发完成，但是版本改动量比较大，担心会引入较多bug
我会先自己多测试一下，这几天会找时间先发布到github上，等大家测试没有问题了，再发布正式版本

**Comment by sjdy521** [comment]
github最新代码已经支持账号密码的登录方式，有兴趣的可以帮忙测试下
需要设置login_type、account、pwd三个参数
```
use Digest::MD5;
Mojo::Webqq->new(login_type=>'login',account=>123456,pwd=>Digest::MD5::md5_hex('QQ账号原始密码') );
```
https://github.com/sjdy521/Mojo-Webqq/blob/master/FAQ.md#3-%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8github%E4%B8%8A%E6%9C%80%E6%96%B0%E7%9A%84%E4%BB%A3%E7%A0%81%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95

**Comment by Love4Taylor** [comment]
@sjdy521试了下 目前体验良好 没有出现问题

_Sent from my Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xhebox** [comment]
@sjdy521 测试通过, 暂时没问题

**Comment by yesmiley** [comment]
测试有效

**Comment by Luxcoldury** [comment]
@sjdy521 账密登陆失效。在尝试登陆失效后，尝试web.qq.com，扫码后也神奇地默屏。改用qrcode登陆成功后，web.qq.com也恢复。怀疑是tx改鉴权了？ptwebqq我看是空的

log:
 [warn] http://s.web2.qq.com/api/getvfwebqq?ptwebqq=&clientid=53999199&psessionid=&t=1517190747 请求(0/5)失败: 502 Bad Gateway

**Comment by sjdy521** [comment]
@Luxcoldury 你反馈的问题据说已经恢复了，再测试看看？

**Comment by Luxcoldury** [comment]
@sjdy521 嗯，账密登陆现在没问题的了。不知道之前问题是出在哪里？我继续看稳定性吧
