### ISSUE TITLE
@有时候不管用

### ISSUE THREAD

**Issue by j1390109557** [sjdy521/Mojo-Webqq#146]
只有刚启动的时候在群里@管用，一会就不管用了 

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LeEco Le X620 发送_

**Comment by StarryFK** [comment]
@好像一直没打算添加的吧？

**Comment by j1390109557** [comment]
@StarryFK 那为什么刚启动的时候在群里@可以说话 一会就不说话了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LeEco Le X620 发送_

**Comment by StarryFK** [comment]
@j1390109557 对不起理解错意思了。。
还以为是说的是：回复功能在群里@人没用，原来是说：@机器人不回复的问题

**Comment by j1390109557** [comment]
@StarryFK 对对，就是@不回复，是什么个情况啊

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LeEco Le X620 发送_

**Comment by StarryFK** [comment]
@j1390109557 机器人这个功能我也没有用过，你自己先诊断一下大概是哪里出的问题，比如服务端有接收到@请求么？回复了没有？回复是不是成功发出去了等等，缩小问题范围，然后再提供自己的机器的情况比如用的是国外的还是过内的机子，用的什么系统，版本多少，perl的版本还有现用的MojoWebqq版本，再等作者来解决吧

**Comment by j1390109557** [comment]
@StarryFK嗯，谢谢你了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 LeEco Le X620 发送_
