### ISSUE TITLE
如何得知讨论组的id呢

### ISSUE THREAD

**Issue by fengallan0** [sjdy521/Mojo-Webqq#147]
如题，请问下如何得到讨论组的id

**Comment by sjdy521** [comment]
和获取好友id，群组id的方式是一样的，你目前获取好友id是通过什么方式？

**Comment by fengallan0** [comment]
你好，谢谢你的回应！
现在好友ID就是好友的QQ号码，群也是一样，就是群号，但是讨论组的ID需要怎么获得呢，我知道用代码调试应该可以获取，想请问有其它简单的方法么

**Comment by fengallan0** [comment]
不好意思，我又仔细看了下，应该是UID，但是讨论组没有UID，那么我想在讨论发信息的话，需要怎么传递参数呢

**Comment by sjdy521** [comment]
讨论组没有uid，只用id，这个id还可能是动态变化的，通过/openqq/get_discuss_info 接口获取到讨论组的id ，接下来使用方法都是一样的，详细情况可以参考 API.md
