### ISSUE TITLE
OpenQQ实现自定义API

### ISSUE THREAD

**Issue by milkice233** [sjdy521/Mojo-Webqq#149]
目前OpenQQ已经有内置API例如/openqq/get_user_info和/openqq/send_friend_message

现在我想问能否实现自定义API，使得向Mojo发出类似/openqq/custom_api请求的时候能够调用相应的函数完成操作呢？看了下Openqq.pm似乎这些API接口已经写死在Openqq.pm里了不知道能不能在不修改Openqq.pm的情况下实现自定义API

**Comment by sjdy521** [comment]
如QQ沟通，该需求实现比较困难，也没有很大的必要性，暂不考虑
