### ISSUE TITLE
在终端打印二维码

### ISSUE THREAD

**Issue by ahxxm** [sjdy521/Mojo-Webqq#150]
可以参考 [这个](https://github.com/mnooner256/pyqrcode/blob/674a77b5eaf850d063f518bd90c243ee34ad6b5d/pyqrcode/__init__.py#L626)

**Comment by sjdy521** [comment]
感谢分享，不过是python的代码，没办法直接使用，不想在安装使用过程中增加太多外部依赖
适合自己喜欢折腾的人，可以通过调用外部命令来实现：

```
$client->on(input_qrcode=>sub{
   my($client,$qrcode_path) = @_;
   qx/qrcode_command $qrcode_path/; #调用外部命令，传入二维码的磁盘路径
});
```
