### ISSUE TITLE
第二天提示重新扫描二维码

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#152]
今天登陆，要重新扫描，这有什么办法解决吗:-D

![image](https://user-images.githubusercontent.com/29328241/30236556-c0c883c6-954e-11e7-81e2-a07c78535ee1.png)

**Comment by fwfmiao** [comment]
![image](https://user-images.githubusercontent.com/29328241/30241216-a4c70798-95b1-11e7-9ce2-4eebe72b50fc.png)
莫名奇妙停止运行，然后再次启动就要重新扫描二维码了:-D今天好几次这样了，都不知道怎么解决:-D

**Comment by fwfmiao** [comment]
好吧 找到原因了😁据说每隔两三天就要扫描一次二维码，真绝望

**Comment by shiyafeng** [comment]
smartqq腾讯已经不维护了 不定时就要重新登陆 你可以试试另一种稳定的方式 https://github.com/shiyafeng/foolqq
