### ISSUE TITLE
讨论组消息报错>_<

### ISSUE THREAD

**Issue by daquexian** [sjdy521/Mojo-Webqq#153]
报错信息：
[error] undefined subroutine Mojo::Webqq::Discuss::uid at /usr/local/share/perl/5.22.1/Mojo/Webqq/Discuss.pm line 19.

\>_< 不会 perl，不知道该怎么处理，我在用 fcm for mojo，然后讨论组消息不能推送，mojo 报了这个错

**Comment by daquexian** [comment]
如果需要更详细的报错信息或者调试步骤的话请说明>_<

**Comment by RikkaW** [comment]
可以 close 了（

**Comment by daquexian** [comment]
(
