### ISSUE TITLE
二维码不应自动获取

### ISSUE THREAD

**Issue by WordlessEcho** [sjdy521/Mojo-Webqq#154]
登录时效后，Mojo WebQQ 会自动获取二维码，但我认为应该改变逻辑，应当让客户端主动发出请求来获取二维码

**Comment by sjdy521** [comment]
可以理解为登录失效后让客户端直接退出？如果需要再次扫码登录 由使用者重新运行程序？

**Comment by WordlessEcho** [comment]
像隔壁 EFB 那样，只有用户确认了才获取二维码登录

**Comment by sjdy521** [comment]
好像没有太大意义，这个主要用在什么场景下呢

**Comment by WordlessEcho** [comment]
自动请求并不总是能得到回应，所以我想还是由用户确认好一点

**Comment by KirbyKFC** [comment]
因为就算自动获取了二维码还是要人为来扫。
所以经常会在起床后发现获取了一堆二维码没人扫自动停止，还是要重新运行程序。

**Comment by sjdy521** [comment]
@KirbyKFC 当前默认是获取10次二维码，如果还没有扫码，就自动退出程序了，这个获取二维码的次数也是可以配置的，如果配置为1次，也就会立刻退出

```
Mojo::Webqq->new(qrcode_count_max  => 10)
```
