### ISSUE TITLE
更新群列表信息失败

### ISSUE THREAD

**Issue by ovear** [sjdy521/Mojo-Webqq#155]
你好，
我在使用您的这个LIB中登录我其中一个QQ时，一直报这个错误，可能是因为我加了一些奇怪的QQ群的原因？

**Comment by ovear** [comment]
经过查看，问题为腾讯Web QQ Api返回错误消息
``
{"retcode":13}
``
可能原因是
1)群数量太多（150个以上）
2)特殊的群导致触发BUG

不知道有没有童鞋加了超过150个群的？

**Comment by idealclover** [comment]
遇到了同样的问题，把群数量降到150以下同样无法解决，不知道特殊的群是指哪种群qwq之前有一段时间是好的今天重启之后一直面临着问题

**Comment by sjdy521** [comment]
摸不透腾讯的脾气…… 暂时没用上面好的办法
