### ISSUE TITLE
好绝望=。= 突然坏了获取不了了

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#161]
![image](https://user-images.githubusercontent.com/29328241/32326208-faa302c2-c00c-11e7-8da1-74087b93aef2.png)
好绝望=。= 突然坏了获取不了了

**Comment by sjdy521** [comment]
看起来是获取扩展信息失败了，扩展信息主要是包含qq号和群号这些唯一id，在你的使用场景中这些扩展信息是否是必须的？

**Comment by fwfmiao** [comment]
获取失败后，调用api发送消息就显示找不到group number，就是/openqq/sendxxx什么的:-D

**Comment by sjdy521** [comment]
我找时间看下 可能是官方把接口又封了…

**Comment by fwfmiao** [comment]
好的，谢谢_(:з)∠)_
今天重新登陆扫描二维码后又好了，不知道什么原因:-D
