### ISSUE TITLE
code|php>>><? print "Hello, world"不响应

### ISSUE THREAD

**Issue by Rstatistics** [sjdy521/Mojo-Webqq#164]
我查了下源码，里面这个地址 https://glot.io/run/php?version=latest 不存在了，run变成了new。我改了也不行，麻烦灰灰大佬看一下哈。另外，建议改成在本地服务器运行其他code就完美啦。多谢！

**Comment by sjdy521** [comment]
抓包看了下仍然存在，glot.io网站调用的这个接口没变过
不响应有可能是你网络问题？我的网络环境下访问glot.io也是比较慢的
