### ISSUE TITLE
 FAIL Installing Mojo::SMTP::Client failed

### ISSUE THREAD

**Issue by yevision94** [sjdy521/Mojo-Webqq#165]
之前在搬瓦工安装可以，现在换了linode的vps，Mojo::SMTP::Client安装不上，卡在building and testing，强制安装又会提示邮件发送失败: Inactivity timeout。
搜索也没找到解决方法，请教大佬有解决方法吗，发邮件扫码还是比较方便的
下面是安装时的报错日记
[build.log](https://github.com/sjdy521/Mojo-Webqq/files/1469769/build.log)

**Comment by bollwarm** [comment]
这种应该不是模块的问题，可能是配的邮件服务器地址或者端口有问题

**Comment by yevision94** [comment]
@bollwarm 你好，发邮件的配置用的是之前的，防火墙也改了。现在想怎样能正常安装这个插件。不知道为啥安装会失败，别的用到的模块都可以安装（无奈···）

**Comment by sjdy521** [comment]
可以试试强制安装

**Comment by yevision94** [comment]
@sjdy521 试了，强制安装会提示邮件发送失败: Inactivity timeout。但是邮件配置那里又和旧的vps的一样的，旧的试了可以，防火墙开了25端口了。

**Comment by sjdy521** [comment]
可能是网络问题？

**Comment by bollwarm** [comment]
telnet下服务器 端口 25

另外如果是阿里云的vps的话，25是底层限制的，你换ssl的协议的stmp端口试试

**Comment by yevision94** [comment]
@bollwarm 是linode的
@sjdy521 这两天试了好几次，真是····
感觉得重装了

**Comment by sjdy521** [comment]
建议加群交流
