### ISSUE TITLE
调用踢除群成员时报异常

### ISSUE THREAD

**Issue by dadiyang** [sjdy521/Mojo-Webqq#168]
openqq/kick_group_member

[error] Can't call method "to_json_hash" on an undefined value at /usr/local/share/perl5/Mojo/Webqq/Plugin/Openqq.pm line 70.

**Comment by bollwarm** [comment]
你要踢成员名字，是啥？

可能是中文，特殊符号混合的把

**Comment by sjdy521** [comment]
估计是没有传递给api正确的kick对象参数
