### ISSUE TITLE
debian9安装失败，'IO::Socket::SSL' is not installed，安装了libssl-dev后，多了Net::SSLeay is not installed

### ISSUE THREAD

**Issue by chrisleung73** [sjdy521/Mojo-Webqq#169]
开始只有'IO::Socket::SSL' is not installed，安装了libssl-dev后，多了Net::SSLeay is not installed

**Comment by Mr-Bubble** [comment]
sudo apt install libnet-ssleay-perl
sudo apt install libio-socket-ssl-perl
