### ISSUE TITLE
不能发送消息，显示[发送失败(登录超时)]

### ISSUE THREAD

**Issue by baboowang** [sjdy521/Mojo-Webqq#17]
不知道是不是我这边的特殊情况，昨天开始，就不能正常发送消息。

消息偶尔能发送成功，大部分都显示[发送失败(登录超时)]，然后就掉线需要重新登录。

**Comment by sjdy521** [comment]
怀疑可能是腾讯发送消息接口变更导致消息发送失败，我近期会尝试定位下问题，有进展会通知到你

**Comment by sjdy521** [comment]
@baboowang 我自己测试了下可以正常发送消息，你遇到的这种情况，可能是腾讯发送消息接口不稳定，偶尔出现发送失败的情况，或者你发送消息中包含某些限制文字，如果连续失败几次就会触发重新登录的操作（需要再次扫描二维码）一般重新登录之后都会变好

连续发送多少次消息失败触发重新登录是通过 send_failure_count_max 属性决定的，默认值是3
你可以尝试增加这个最大次数，比如：

$client = Mojo::Webqq->new(send_failure_count_max =>10)

但腾讯本身发送消息失败的情况暂时没办法改善
