### ISSUE TITLE
无法显示讨论组和群成员的备注名

### ISSUE THREAD

**Issue by TYPEmber** [sjdy521/Mojo-Webqq#170]
好友私聊可以正常显示备注，但是群和讨论组中发言则无法显示备注名称

**Comment by sjdy521** [comment]
你的意思是，群里发言的人同时也是你的好友，这种情况下，显示的群消息没有好友备注名称？
如果我这种情况，是因为程序没有去特意判断群成员是否是你的好友，而且你可以对好友设置备注，同时对这个好友在某个群里又设置另外一个备注，考虑到这种情况下，程序默认是只显示群成员在群里的备注名称，如果没有备注名称，就只会显示在群里的昵称

**Comment by TYPEmber** [comment]
谢谢详细解释，群消息我试了试确实是这样，但是讨论组的话没有备注这项功能。
能否考虑直接使用对没有群备注的加以是否是好友的判断，并直接显示好友备注？

2017年11月30日 15:16，"sjdy521" <notifications@github.com>写道：

**Comment by sjdy521** [comment]
github最新代码已经支持，有空可以帮忙测试下

https://github.com/sjdy521/Mojo-Webqq/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试
