### ISSUE TITLE
消息上报接口，特定消息才上报

### ISSUE THREAD

**Issue by jansyhung** [sjdy521/Mojo-Webqq#174]
配了上报接口后，是不是会把收到的消息都上报？
我有个这样的需求，群里@自己的消息，才通过上报接口发送，其他消息忽略、不上报，这样能否实现？

**Comment by sjdy521** [comment]
当前是所有消息都上报 没办法做上报过滤，建议你把所有消息都接收之后，自己再过滤想要的艾特消息？
艾特的消息也只是纯文本的 自己做一下消息内容的正则匹配就行了
