### ISSUE TITLE
get_group_info 不能返回组员的uid

### ISSUE THREAD

**Issue by HeroSizy** [sjdy521/Mojo-Webqq#177]
只有以下这些键值：
`card` `city` `client_type`  `country` `id` `name` `province` `sex` `state`

**Comment by sjdy521** [comment]
你当前使用的是哪个版本？

**Comment by HeroSizy** [comment]
2.1.4版本的

**Comment by sjdy521** [comment]
官方做了限制导致原本的功能失效，目前已经无法正常获取到QQ号（uid ) 
解决办法我还在研究……

**Comment by HeroSizy** [comment]
好的，辛苦啦

**Comment by sjdy521** [comment]
新版本已经解决，但方式并不是非常完美，参考 https://github.com/sjdy521/Mojo-Webqq/issues/183
