### ISSUE TITLE
/openqq/get_friend_info 无法返回uid

### ISSUE THREAD

**Issue by WandW** [sjdy521/Mojo-Webqq#178]
Windows版本2.1.4 /openqq/get_friend_info 无法返回uid

**Comment by sjdy521** [comment]
官方做了限制导致原本的功能失效，目前已经无法正常获取到QQ号（uid )

**Comment by sjdy521** [comment]
已修复
需要更新到 v2.1.5版本
由于腾讯的限制，获取uid需要使用QQ登录密码进行授权
授权过程涉及到复杂的rsa计算，需要依赖一个新的模块 Webqq::Encryption
并且需要在程序启动参数中添加授权密码，具体操作方式如下：

1、安装Webqq::Encryption模块，安装方法参考：
https://metacpan.org/pod/release/SJDY/Webqq-Encryption-1.6/lib/Webqq/Encryption.pod

2、启动参数中增加pwd
Mojo::Webqq->new(pwd=>'你的QQ账号登录密码的32位md5值');
