### ISSUE TITLE
/openqq/get_friend_info 扩展信息接口失效

### ISSUE THREAD

**Issue by New-GitHub** [sjdy521/Mojo-Webqq#179]
/openqq/get_friend_info 无法返回uid，日志显示：更新好友扩展信息失败、更新群扩展信息失败。Mojo-Webqq Version2.1.4。

**Comment by sjdy521** [comment]
官方做了限制导致原本的功能失效，目前已经无法正常获取到QQ号（uid )

**Comment by New-GitHub** [comment]
多谢作者答复，已知。😘




在2018年01月04日 21:01，sjdy521 写道：

官方做了限制导致原本的功能失效，目前已经无法正常获取到QQ号（uid )

**Comment by sjdy521** [comment]
已修复
需要更新到 v2.1.5版本
由于腾讯的限制，获取uid需要使用QQ登录密码进行授权
授权过程涉及到复杂的rsa计算，需要依赖一个新的模块 Webqq::Encryption
并且需要在程序启动参数中添加授权密码，具体操作方式如下：

1、安装Webqq::Encryption模块，安装方法参考：
https://metacpan.org/pod/release/SJDY/Webqq-Encryption-1.6/lib/Webqq/Encryption.pod

2、启动参数中增加pwd
Mojo::Webqq->new(pwd=>'你的QQ账号登录密码的32位md5值');
