### ISSUE TITLE
请求二维码图片的链接为什么t是随机数？如何分析的？

### ISSUE THREAD

**Issue by autodataming** [sjdy521/Mojo-Webqq#18]
请求二维码图片的链接为什么t是随机数？如何分析的？
https://ssl.ptlogin2.qq.com/ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.02650754311793857

**Comment by autodataming** [comment]
https://ssl.ptlogin2.qq.com/ptqrshow?appid=501004106&e=0&l=M&s=5&d=72&v=4&t=0.45266348909137744

**Comment by autodataming** [comment]
appid=501004106
d=72
e=0
l=M
s=5
t=0.6065851819467937
v=4

**Comment by sjdy521** [comment]
看 https://ui.ptlogin2.qq.com/js/10149/mq_comm.js 里函数的定义

`get_qrlogin_pic: function() {
        var t = "ptqrshow",
        e = (pt.isHttps ? "https://ssl.": "http://") + "ptlogin2." + g_domain + "/" + t + "?";
        return 2 == pt.regmaster ? e = "http://ptlogin2.function.qq.com/" + t + "?regmaster=2&": 3 == pt.regmaster && (e = "http://ptlogin2.crm2.qq.com/" + t + "?regmaster=3&"),
        e += "appid=" + g_appid + "&e=0&l=M&s=5&d=72&v=4&t=" + Math.random()
    },`

t的取值是 Math.random()
