### ISSUE TITLE
更新扩展信息失败

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#180]
更新好友扩展信息失败
更新群扩展信息失败

**Comment by sjdy521** [comment]
官方做了限制导致原本的功能失效，目前已经无法正常获取到QQ号（uid ) 所以导致通过uid来发送消息都会失败，只能先按照id来发送消息，但是id每次扫码都会变化

**Comment by sjdy521** [comment]
已修复
需要更新到 v2.1.5版本
由于腾讯的限制，获取uid需要使用QQ登录密码进行授权
授权过程涉及到复杂的rsa计算，需要依赖一个新的模块 Webqq::Encryption
并且需要在程序启动参数中添加授权密码，具体操作方式如下：

1、安装Webqq::Encryption模块，安装方法参考：
https://metacpan.org/pod/release/SJDY/Webqq-Encryption-1.6/lib/Webqq/Encryption.pod

2、启动参数中增加pwd
Mojo::Webqq->new(pwd=>'你的QQ账号登录密码的32位md5值');

**Comment by yesmiley** [comment]
加了代码 显示拓展信息授权成功 但还是拓展信息获取失败
