### ISSUE TITLE
测到该账号有其他运行中的客户端

### ISSUE THREAD

**Issue by adee4ever** [sjdy521/Mojo-Webqq#184]
这个怎么解决呢？更新后一直显示这个 ，以前那个进程都关闭了，VPS都重启了。不知道哪里出了问题

**Comment by sjdy521** [comment]
有时候是程序检测异常了，可以清理掉/tmp/mojo_webqq_xxxx.pid文件就可以了

**Comment by leon0520** [comment]
升级到了2.1.6,一直提示[warn] 检测到该账号有其他运行中的客户端(pid:22370), 请先将其关闭，
尝试过清理了/tmp/mojo_webqq_xxxx.pid
