### ISSUE TITLE
Mojo-Webqq API 连接超时，监听5000端口后请求失败。

### ISSUE THREAD

**Issue by New-GitHub** [sjdy521/Mojo-Webqq#185]
https://sm.ms/api/upload 请求(1/5)失败: - Connect timeout

**Comment by sjdy521** [comment]
https://sm.ms/api/upload 这个apihi是用来上传二维码的，失败了也不影响扫码登录
5000端口请求失败具体是怎么个失败？给的信息太少了

**Comment by New-GitHub** [comment]
好的，我更新了新版本可以了。
