### ISSUE TITLE
提示：未设置账号授权密码，无法获取扩展信息。

### ISSUE THREAD

**Issue by New-GitHub** [sjdy521/Mojo-Webqq#186]
参考https://github.com/sjdy521/Mojo-Webqq/issues/183
添加Mojo::Webqq->new(pwd=>Digest::MD5::md5_hex('xxx'));
后执行后登陆成功。
终端提示：
[warn] 未设置账号授权密码，无法获取扩展信息，已忽略
[warn] 无法支持获取扩展信息
[warn] 无法支持获取扩展信息

**Comment by sjdy521** [comment]
从启动开始完整的日志发出来看看

**Comment by New-GitHub** [comment]
不好意思，脚本写错了。
