### ISSUE TITLE
Openqq加载失败 不能发送消息

### ISSUE THREAD

**Issue by yesmiley** [sjdy521/Mojo-Webqq#187]
腾讯云服务器 安全组已放通 推送到手机正常 但是无法进行回复

提示错误信息：
[error] 插件[ Mojo::Webqq::Plugin::Openqq ]执行错误: Can't create listen socket: Cannot assign requested address at /usr/local/share/perl5/Mojo/IOLoop.pm line 126.

**Comment by sjdy521** [comment]
Openqq插件不要设置host参数 或者host参数设置为”0.0.0.0”
