### ISSUE TITLE
图床 api那块能给个详细的例子吗？

### ISSUE THREAD

**Issue by lemos1235** [sjdy521/Mojo-Webqq#194]
比如 vim-cn那个接口是要怎么做？

**Comment by sjdy521** [comment]
vim-cn接口是指什么？

**Comment by sjdy521** [comment]
我知道你说的是什么意思了 我晚点把api的底层发送方法发出来（其实你自己浏览器抓包也能知道是如何发请求的）

**Comment by lemos1235** [comment]
@sjdy521 がんばれ！

**Comment by sjdy521** [comment]
采用的是HTTP POST上传文件的通用协议，multipart/form-data方式
原始的HTTP报文是这样的：
```
POST / HTTP/1.1
Host: img.vim-cn.com
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryaiGtr7plyFdR3y7r

------WebKitFormBoundaryaiGtr7plyFdR3y7r
Content-Disposition: form-data; name="image"; filename="a.jpg"
Content-Type: image/jpeg

------WebKitFormBoundaryaiGtr7plyFdR3y7r--
```
curl命令的使用方式是这样的：
```
curl -F 'name=@screenshot.png' http://img.vim-cn.com/
```

**Comment by lemos1235** [comment]
这个不是将  qq里的图片自动转换成链接，是吧？

**Comment by Hagb** [comment]
@sjdy521 你好，我在本地搭建了服务器，设置了之后还是收不到图片，群里面发了图片或私聊发了图片之后没有任何反应。
`$client->load("IRCShell",data=>{load_friend => 1,upload_api => "http://127.0.0.1:8888/"});`

**Comment by sjdy521** [comment]
@lemos1235 是自动转成连接
@Hagb  但是我忘记说一点了：qq现在不支持接收图片，所以这个也没什么用了，微信支持接收图片

**Comment by Hagb** [comment]
@sjdy521 谢谢。

**Comment by lemos1235** [comment]
@sjdy521 不对啊。我看人家写的 telegram与irc的互联机器人可以显示图片啊。
