### ISSUE TITLE
SmartReply 的 keyword 不生效

### ISSUE THREAD

**Issue by huangzhongzhang** [sjdy521/Mojo-Webqq#195]
配置keyword之后，群聊天不生效，反而私聊生效了。

<img width="694" alt="qq20180126-153524 2x" src="https://user-images.githubusercontent.com/13826425/35429376-bf98d62c-02ae-11e8-8265-7e3399905dcd.png">
<img width="687" alt="qq20180126-153615 2x" src="https://user-images.githubusercontent.com/13826425/35429377-bfcf62e6-02ae-11e8-9937-8d847455370f.png">

**Comment by sjdy521** [comment]
is_need_at是否设置了1？
2.1.7版本 is_need_at 和 keyword 会分别生效，彼此各自执行各自的逻辑，

**Comment by huangzhongzhang** [comment]
```
        is_need_at      => 1,  #默认是1 是否需要艾特才触发回复 仅针对群消息
        keyword         => [qw(NPC npc)], #触发智能回复的关键字
```

都设置了，版本也是最新的。但是keyword在群消息中不生效，反而在私聊中生效了。

**Comment by sjdy521** [comment]
这个行为当前好像是正常的 因为is_need_at表示需要艾特才触发没有艾特就不会触发

**Comment by sjdy521** [comment]
已经修复SmartReply插件 is_need_at 和 keyword 无法同时生效的问题
