### ISSUE TITLE
无法接受私聊消息可以接收到群聊消息

### ISSUE THREAD

**Issue by MichaelPanPRC** [sjdy521/Mojo-Webqq#196]
使用FFM客户端，客户端内已经开启接收私聊消息，服务器端内无显示，客户端也没有显示。

**Comment by Luxcoldury** [comment]
@MichaelPanPRC 同样问题，不过我直接登web.qq.com也一样发得出但收不到消息，可能是tx的问题。你也试一下？

**Comment by MichaelPanPRC** [comment]
@Luxcoldury我一会试一下

**Comment by yesmiley** [comment]
我也是，刚才发现一直收不到，开始以为是vps又炸了，然后测试发现，用小号给大号发，私发就不行，群聊就有，而且ssh里面也没有显示（说明mojo webqq本身就没收到消息）

**Comment by MichaelPanPRC** [comment]
@yesmiley嗯

**Comment by dugreen** [comment]
难道是我昨天写了个消息轰炸的脚本，给tx的服务器搞炸了??我记得也就循环了几百次啊！！

**Comment by MichaelPanPRC** [comment]
@dugreen233333等修复吧

**Comment by MichaelPanPRC** [comment]
@dugreen 233333等修复吧

**Comment by kzw200015** [comment]
我也是这样

**Comment by sjdy521** [comment]
这个应该不是 Mojo-Webqq 本身的问题吧

**Comment by MichaelPanPRC** [comment]
@sjdy521 我们说是tx的问题啊 Webqq的事。

**Comment by sjzhangqiang** [comment]
@sjdy521 大神啊，我私聊只能发送给对方，对方发送的信息到我centos控制台无法显示，就好像没接收到。后来日志级别调整为debug，就一直打出
忽略接收消息中的异常状态码[ 100012 ]，大神求助啊！

**Comment by sjdy521** [comment]
@sjzhangqiang debug级别的日志“忽略接收消息中的异常状态码[ 100012 ]” 可以忽略 并没有什么影响
最近很多人反馈无法收到私聊消息，webqq原生是不支持群成员私聊的，只能收到好友私聊消息
如果收不到好友消息 可能是官方出了什么问题 这个我会近期找时间看看

**Comment by MichaelPanPRC** [comment]
@sjdy521我们反馈的就是好友私聊

**Comment by bslc981010** [comment]
确实今天发现收不到了

**Comment by 75115200** [comment]
同样是收不到私聊的消息，只能收到群聊

**Comment by iVeego** [comment]
同样反馈，接收不到好友的私聊消息。

**Comment by PhotonQuantum** [comment]
大概是官方爆炸了 开启 http_debug 完全看不到私聊接收的消息 自己私聊发送的倒看得到

**Comment by yesmiley** [comment]
刚收到一条私聊推送

**Comment by Luxcoldury** [comment]
@yesmiley 刚重新试了，并收不到。可以试试从web.qq.com登陆，看tx官方收的到么？我之前试过并收不到，应该并不是这边的问题

**Comment by yesmiley** [comment]
@Luxcoldury 一个小时前确实收到了一条 然后小号测试了一条也收到了 现在测试又不行了

**Comment by yesmiley** [comment]
刚刚的截图的 又有动静了 两条私聊 FFM只收到了一条 可能在恢复 但还是不稳定

![23ab95ee734f619e467babc030eec292](https://user-images.githubusercontent.com/32222791/35898151-c281c92a-0bff-11e8-9063-6120ecd00766.jpg)

**Comment by MichaelPanPRC** [comment]
@yesmiley 嗯 测试了，现在可以收到，有些不稳。在观察，有时候有延迟。

**Comment by Luxcoldury** [comment]
@yesmiley @MichaelPanPRC 我这里也观察到已恢复

**Comment by PhotonQuantum** [comment]
好像是tx升级造成的 现在已经恢复
