### ISSUE TITLE
在VPS下输出信息都是问号？

### ISSUE THREAD

**Issue by netcan** [sjdy521/Mojo-Webqq#20]
debian的vps

**Comment by sjdy521** [comment]
Hi 应该是输出乱码了
通常会自动检测输出编码，但也有检测失败的情况，你可以手动设置下输出编码，比如：

···$client = Mojo::Webqq->new(qq=>xxxxx,log_encoding=>"utf8")···

···$client = Mojo::Webqq->new(qq=>xxxxx,log_encoding=>"gbk")···

**Comment by netcan** [comment]
嗯，解决了。谢谢了
