### ISSUE TITLE
最新帐号密码已经无法登录

### ISSUE THREAD

**Issue by cjjdaq** [sjdy521/Mojo-Webqq#202]
最新帐号密码已经无法登录

**Comment by sjdy521** [comment]
我这里看还是ok的呀

**Comment by ShekBoy** [comment]
![screenshot_20180223112719](https://user-images.githubusercontent.com/22590886/36576605-a8713810-188c-11e8-9efc-116d6b9c525b.png)
我也是一直都不能用账号密码方式登录，就只显示登录失败...

**Comment by ShekBoy** [comment]
@sjdy521 我是跟着这人的折腾日志改的 https://love4taylor.me/mojo-fcm-qq.html
account 的qq号那里我改成了1234567890，其他都是一样的
 
[start.zip](https://github.com/sjdy521/Mojo-Webqq/files/1751235/start.zip)

**Comment by sjdy521** [comment]
@ShekBoy 程序写的没问题，采用账号密码的登录方式，这段代码已经内置了，可以删掉了，不然会造成重复执行relogin两次

> $client->on(
>     model_update_fail => sub {
>         $client = shift;
>         $client->relogin();
>     }
> );

Mojo::Webqq->new()里可以再加一个参数 log_level=>"debug" 这样可以打印更多的登录过程日志
目前看，账号密码一直无法正常登录应该是账号登录所在地发生较大变化，则腾讯服务器可能需要你输入图片验证码，这样就很难实现自动化操作，为了避免这种情况，你需要尽量在pl脚本所在的网络中用浏览器多登录一下 http://qun.qq.com 让腾讯服务器消除登录异常的判断

你可以在服务端搭建ssh隧道，socks5代理，支持SSL转发（CONNECT方法）的http代理等方式，然后浏览器通过服务端代理访问

详情参考issue： https://github.com/sjdy521/Mojo-Webqq/issues/183

**Comment by ShekBoy** [comment]
感谢！但加了参数看日志，依然是只出现登陆失败的信息
已试过挂openvpn，或者跟着这教程https://blog.twofei.com/506/ 用ssh隧道在浏览器登陆后依然登陆失败，已确认过ip已经变为服务端的
![screenshot_20180224112109](https://user-images.githubusercontent.com/22590886/36625210-626ae940-1956-11e8-8724-4effcd79573b.png)

**Comment by sjdy521** [comment]
@ShekBoy 要ssh隧道之类的方式浏览器多登录几天，没有那么快的，每天记得登录一两次，日久天长才能看到效果，其他人也有碰到类似的情况，最终都ok了

**Comment by ShekBoy** [comment]
@sjdy521 好的，感谢，那我继续试试一个礼拜看看

**Comment by cjjdaq** [comment]
已经找到问题所在，换了自家的群晖顺利登陆，可能是用国外的vps，突然不是本地登陆需要验证码。

**Comment by ShekBoy** [comment]
@cjjdaq 咦，我的也是群晖，虽说不是同一个IP但也都是香港，也是不能登陆...其实登录qun.qq.com也没提示要验证码啊...

**Comment by sakuyamaij** [comment]
一样的情况，今天刚搭建好
```
[18/02/26 14:39:38] [info] 开始账号密码方式登录...
[18/02/26 14:39:39] [error] 账号登录失败: 可能因为登录环境变化引起，解决方法参见：https://github.com/sjdy521/Mojo-Webqq/issues/183
[18/02/26 14:39:39] [info] 更新个人信息...
[18/02/26 14:39:39] [info] 更新好友信息...
[18/02/26 14:39:39] [warn] 无法支持获取扩展信息
[18/02/26 14:39:43] [info] 更新群列表信息...
```
@ShekBoy 请问你搭建好几天了。目前我也只能每天登录qun.qq.com几次试试，虽然网页登录每次都直接登进去，毫无验证码之类的东西

**Comment by ShekBoy** [comment]
@sakuyamaij 搭建了应该有两个月以上了，以前一直二维码登陆，尝试帐号密码登录就上个礼拜的事，用ssh隧道连续登录qun.qq.com就前天才开始，我还是先试试一段时间连续登录看看

**Comment by sjdy521** [comment]
后续我再考虑把输入验证码的过程也实现一下 不过这个验证码是采用拼图解释的 单纯在终端上很难完成操作，所以当时才没有去实现

**Comment by ShekBoy** [comment]
@sjdy521 今天就连续登录一个礼拜了，依然必须扫二维码，我耐心等你以后更新好了，感谢！

**Comment by sakuyamaij** [comment]
@ShekBoy 我今天已经可以账密登录了，而且我那个vps的地址前几天还被墙了。加油，多等几天试试

**Comment by ShekBoy** [comment]
@sakuyamaij emmmm，这么多天还是不成功，其实报错也不一样，不知道是不是我有ipv6的问题，我还是等更新好了
