### ISSUE TITLE
安装成功为什么没法使用

### ISSUE THREAD

**Issue by tangxiadi** [sjdy521/Mojo-Webqq#203]
![2018-02-21 10 04 52](https://user-images.githubusercontent.com/9555093/36484226-82dba4c6-1753-11e8-878c-7deda973fe55.png)

**Comment by sjdy521** [comment]
注意看截图第三行开始的感叹号开头的提示，因为你是非root环境下安装的，有些环境存在问题，可以根据指引操作试试 如果还是搞不定可以加群讨论，或者干脆切换到root环境下重新安装

**Comment by sjdy521** [comment]
解决方法：
1、切换到root账号下重新安装使用

2、在非root账号下依次执行如下操作（**不要在任何命令前面加sudo**）
1）安装local::lib模块 `cpanm --local-lib=~/perl5 local::lib  && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)`
2)把相关环境变量写入启动文件中 `echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >>~/.bashrc`
