### ISSUE TITLE
GCM插件的群组设置功能出错

### ISSUE THREAD

**Issue by Hzbeta** [sjdy521/Mojo-Webqq#205]
设置了allow_group以后，就无法推送所有群组消息，服务端能显示，不设置的时候可以收到。
希望能修复一下

**Comment by sjdy521** [comment]
没太理解上表述
allow_group参数本身的含义就是只允许列出来的群组，其他不在列表里的就忽略
如果希望推送所有群，直接去掉这个参数就行了，这个并不是bug吧

**Comment by Hzbeta** [comment]
就是设置allow_group以后，不管是允许的还是不允许的都不能推送，不设置的话就能推送。

**Comment by xzsk2** [comment]
同样的问题，但是把群号改成群名称填进去就能正常推送了

**Comment by sjdy521** [comment]
因为现在获取群号需要账号密码方式成功登录才可以，否则就尽量用群名称吧

**Comment by Hzbeta** [comment]
我用的是账号密码登录啊，也是不行的

**Comment by sjdy521** [comment]
@Hzbeta 设置了账号密码登录，还要根据日志确认下有没有登录成功，有没有成功获取导"扩展信息"
可以把启动之后到开始接收消息的这部分运行日志发出来我研究下
