### ISSUE TITLE
能否参考隔壁FFM-Mojo-WebQQ 的方式对[图片]进行处理显示？

### ISSUE THREAD

**Issue by yesmiley** [sjdy521/Mojo-Webqq#208]

**Comment by tusooa** [comment]
在它的代码里搜索了一下，其策略是「消息为空时返回[图片]」。
Webqq 本身**并不**支持图片。只是一条讯息中如果只有图片，它还是会被接收，内容为空。
这样并没有考虑一条消息中图文并存的情况。况且，我们并不能够保证内容为空的讯息一定就是图片。若这样处理，可能会使得一些用户困惑，以为Webqq开始支持图片(或者至少能知道讯息中某位置出现了图片)了。
您可以考虑在代码中添加这么一段来模拟这个效果。

```perl
$client->on(receive_message => sub
{
    my (undef, $msg) = @_;
    $msg->{content} = '图片' if ! length $msg->{content};
});
```
