### ISSUE TITLE
被封号了。。。

### ISSUE THREAD

**Issue by Droid-MAX** [sjdy521/Mojo-Webqq#209]
涉嫌业务违规操作(如批量登录等)

**Comment by sjdy521** [comment]
有什么日志或者截图参考下吗

**Comment by Droid-MAX** [comment]
猜测可能的原因是在使用账号密码方式登录时默认的失败重试次数超出了tx的限制，从而被检测出"批量登录"的行为，日志中确定没有error

**Comment by sjdy521** [comment]
一般失败之后不会有太多重试次数的

**Comment by huangzhongzhang** [comment]
正常的，我都被封了好几次了，解封后换个密码继续用。有可能是被人举报了。

**Comment by Droid-MAX** [comment]
我也有过这方面的猜测
