### ISSUE TITLE
这个QQ如何保证其稳定性？

### ISSUE THREAD

**Issue by Anonymous-W** [sjdy521/Mojo-Webqq#213]
用来做一个项目，时不时有各种原因就停止了，请问有什么推荐的保证稳定性的措施吗？

**Comment by Anonymous-W** [comment]
还有就是经常性出现502

**Comment by sjdy521** [comment]
@Anonymous-W 保证不了，对稳定性有要求的项目不建议使用这个

**Comment by Anonymous-W** [comment]
那更新信息失败这些是否会影响发消息呢？

**Comment by sjdy521** [comment]
大部分情况下不影响发送消息
但是webqq长时间登录会登录状态过期，这种情况下更新信息会全部失败，发送消息也会发不出去
碰到这种情况，程序会检测到，然后自动调用relogin进行重新扫码登录

**Comment by smaugx** [comment]
@Anonymous-W  我是扫码登录的，目前采取的办法是 定时脚本每隔一定时间（比如我设置了 8h）强制杀死 mojo-webqq 然后重启.

截至目前已经稳定在线 38h, 不知道还能持续在线多久！

**Comment by sjdy521** [comment]
@smaugx 有点奇怪，客户端强制杀死重启应该是没作用的，登录的有效期（当前一般是48h）是在服务端决定的

**Comment by smaugx** [comment]
@sjdy521   确实是，大概在 47h 的时候掉线了。扫码登录有这个限制，密码登录也有这个限制吗？
目前我还没有成功使用密码登录上。
@sjdy521  关于自动化，你有什么建议吗？你是怎么做的？

**Comment by Anonymous-W** [comment]
我已经放弃了，，，，这玩意儿稳不稳真的是看腾讯爸爸心情的

**Comment by smaugx** [comment]
@Anonymous-W @sjdy521   通过密码登录的方式，每 8 h kill 一次强制重新登录，kill 之后同时删除 
```
/tmp/mojo_webqq_cookie_2372961723.dat  /tmp/mojo_webqq_pid_2372961723.pid  /tmp/mojo_webqq_state_2372961723.json
```
这三个缓存数据，截至目前，已经在线 近 7 天时间了。（这里的在线可能有点不准确，应该说已经自动化在线 7 天）。
大概看了下日志文件，重新登录的时间大致在 6 s 左右，这 6 s 内若有监控消息（使用了 openqq http 接口）发送可能会丢失，需要注意，不过可以适当设置监控消息发送超时时间为 10 s，这样不会丢消息。

**Comment by sjdy521** [comment]
密码的登录方式，基本可以一直在线，即使自己不进行kill

**Comment by Anonymous-W** [comment]
@smaugx @sjdy521 好的，谢谢两位
