### ISSUE TITLE
无法支持获取扩展信息

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#215]
![image](https://user-images.githubusercontent.com/29328241/38911020-20f91f2c-42ff-11e8-839e-821e6d05258a.png)

一直提示“无法支持获取扩展信息”，使用的方式是扫码登录

**Comment by fwfmiao** [comment]
![image](https://user-images.githubusercontent.com/29328241/38926293-bdb91864-4334-11e8-8065-566b1301b3f3.png)
改成密码了，现在一直登录失败_(:з」∠)_

**Comment by sjdy521** [comment]
看日志，似乎使用的是旧版本？
账号密码登录参考这里：https://github.com/sjdy521/Mojo-Webqq/issues/183

**Comment by fwfmiao** [comment]
是ip问题_(:з」∠)_换了个新ip，装了个ss，连上去反复登陆了一段时间。。。可以了
然后第二天qq被禁，改密，正在网页反复登陆ing，。，，

**Comment by sjdy521** [comment]
如果只是为了调用api接口发送消息，可以直接使用昵称或者群名称来发送，github最新代码已经支持了
http://127.0.0.1:5000/openqq/send_group_message?name=xxxx&content=hello

**Comment by remini1998** [comment]
上报一个我发现的事情....
一开始加载失败，提示显示和这个issue一模一样，/openqq/get_group_info只能显示基本信息，没有群成员。
但是docker挂了一天没关就好了，原因不明。
