### ISSUE TITLE
禁言时常为秒没问题吗

### ISSUE THREAD

**Issue by Mahua233** [sjdy521/Mojo-Webqq#217]
貌似手动禁言最低是分钟，或是说qq会自动取整？

**Comment by sjdy521** [comment]
这个是腾讯的限制，最低一分钟

**Comment by Mahua233** [comment]
@sjdy521 我的意思是 貌似手动禁言好像只能是分钟禁言 那禁言的那个接口是不是可以写成分钟的形式
如果被发现是机器人的话我感觉会被tx当成外挂

**Comment by sjdy521** [comment]
接口已经改成分钟单位了
