### ISSUE TITLE
能否上线一个管理员撤回群成员消息的功能呢

### ISSUE THREAD

**Issue by houtaijun** [sjdy521/Mojo-Webqq#221]

**Comment by bollwarm** [comment]
那个不支持把，pc端都不支持，webqq就更不要想了，去试试去webqq端能支持就可以

**Comment by houtaijun** [comment]
看了有个群的机器人，会自动撤回，但是不知道他们怎么实现的

**Comment by sjdy521** [comment]
基于网页QQ，不支持消息撤回
其他支持的机器人，应该是基于pc/移动端协议实现的，已经超出能力范围
