### ISSUE TITLE
感谢这么完美的作品

### ISSUE THREAD

**Issue by plutoid** [sjdy521/Mojo-Webqq#222]
打赏5元请喝杯果汁~~

**Comment by tusooa** [comment]
感谢您对本项目的支持，您可以移步 https://github.com/sjdy521/Mojo-Thanks 留个名。

**Comment by sjdy521** [comment]
@tusooa 已添加到Thanks列表
@plutoid 感谢给出如此高的赞誉，果汁已喝到~
