### ISSUE TITLE
获取数据验证参数  502 Bad Gateway

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#227]
![image](https://user-images.githubusercontent.com/29328241/39434141-502574e2-4cca-11e8-92c7-60a6703b2b7f.png)
一直在打印这个错误
_(:з」∠)_ i need help

**Comment by kzw200015** [comment]
腾讯的锅

**Comment by yanyumihuang** [comment]
@kzw200015 持续时间太长了，十二个小时了一直502.

**Comment by fwfmiao** [comment]
真是个悲伤地故事，偶尔能连上，偶尔会报错

**Comment by smaugx** [comment]
过了个节，发现已经不可用了。同样出现了上述的错误，也登录成功了，只是更新好友信息等失败，也无法发送消息。

**Comment by sdhou** [comment]
我也是 坏了几天了
http://s.web2.qq.com/api/get_user_friends2 请求(1/5)失败: 502 Bad Gateway

**Comment by yanyumihuang** [comment]
快崩溃了，一会好，一会坏

**Comment by sjdy521** [comment]
以前也有出现类似的情况，都是过段时间自己恢复了，只能等腾讯修复吧

**Comment by yanyumihuang** [comment]
@sjdy521 我这里
![image](https://user-images.githubusercontent.com/26965886/39507269-c82a2e88-4e0f-11e8-9e56-882551191ffe.png)
今天连网页版都没法登陆了，点击‘立即体验后就跳转到qq互联了

**Comment by fwfmiao** [comment]
网页版一直不能登陆，感觉是腾讯要把这个关了┓( ´∀` )┏ 但是连还是能连得上

**Comment by linchunquan** [comment]
[warn] http://s.web2.qq.com/api/getvfwebqq?ptwebqq=62cc06c67219d60d6ed562b0b5a0079fc9516067e9a921e7295d654c473b66ab&clientid=53999199&psessionid=&t=0.953221694039204 请求(0/5)失败: 502 Bad Gateway

今天登录持续出现上述错误，请问如何解决修复，谢谢！

**Comment by Naruone** [comment]
我也碰到同样的问题,今天突然不行了
