### ISSUE TITLE
现在账号密码登录已经凉了吗

### ISSUE THREAD

**Issue by fwfmiao** [sjdy521/Mojo-Webqq#232]
![image](https://user-images.githubusercontent.com/29328241/40342222-ecd0c1a0-5dbb-11e8-997d-0bfdd89e0e7c.png)

现在账号密码登录已经凉了吗，一直显示time out，现在也只能二维码了

**Comment by kzw200015** [comment]
+1

**Comment by sjdy521** [comment]
貌似是这样，只能先使用二维码登录

**Comment by AkazaDorian** [comment]
但是实际上你给一个错误的账号密码他是能识别出来的……不知道是哪里出问题导致没法登陆

**Comment by sjdy521** [comment]
@AkazaDorian 账号密码登录的功能本身应该没什么问题，但是这个登录是针对qun.qq.com等页面的
这个页面的登录状态以前是可以共享给网页QQ的web2.qq.com页面，从而实现了网页QQ的自动登录（实际上是从其他地方登录了然后这里就免登录） 但是最近腾讯应该是取消了这二者的登录状态共享，所以就没办法实现网页QQ自动登录了
