### ISSUE TITLE
消息中有(<)左尖括号时会获得的消息中会有右尖括号(>)

### ISSUE THREAD

**Issue by changgeshi** [sjdy521/Mojo-Webqq#238]
左尖括号后面是数字没有这个问题，是字符串则不行。
如图：
![1](https://user-images.githubusercontent.com/18047650/41073705-10cdabf6-69f4-11e8-8588-7db4dc8ed08a.jpg)

**Comment by tusooa** [comment]
您的问题描述过于模糊，是发送讯息还是接收讯息？发送了什么，接收了什么？预期应该接收到什么？

不幸的是，Webqq并不能支持发送真正的`<`和`>`，在网页版，这表现为所有发送出的讯息中，`<`和`>`都被替换成了`&lt;`和`&gt;`。本项目采取了一个 workaround，即将`<`和`>`替换为它们的中文版本。这段的说明可能将对您的问题有所帮助，但是我不能确定。为了获得更有针对性的帮助，您需要提供更详细的信息。
