### ISSUE TITLE
docker输出日志乱码

### ISSUE THREAD

**Issue by AsinRay** [sjdy521/Mojo-Webqq#239]
使用docker 方式启动，并将日志重定向到webqq.log文件，打开文件后发现有乱码.
示例如下：
[18/06/05 09:44:45] [[36m群消息[0m] [36m超人类未来的总|【心域】战舰世界亚服 : [0m[36m一头雾水 质量效应？[0m

**Comment by sjdy521** [comment]
docker run -it --env  MOJO_WEBQQ_DISABLE_COLOR=1
乱码的部分是一些颜色控制的代码，你的docker环境终端不支持彩色显示，可以在docker镜像启动时通过环境变量 设置 MOJO_WEBQQ_DISABLE_COLOR=1 来禁止彩色输出
