### ISSUE TITLE
GroupManage插件改进意见

### ISSUE THREAD

**Issue by snail007** [sjdy521/Mojo-Webqq#24]
群管理插件，强烈希望能指定管理某个qq群，可以自己设置一个或多个qq群号，进行管理。
还有就是现在发图片限制无法工作了，希望能看情况修复。

**Comment by sjdy521** [comment]
新增两个参数进行指定群或禁止群
···
$client->load("GroupManage",data=>{
    allow_group => ["PERL学习交流"],  #可选，允许插件的群，可以是群名称或群号码
    ban_group   => ["私人群",123456], #可选，禁用该插件的群，可以是群名称或群号码
});
···

发图限制失效问题无法解决，因为腾讯的限制导致完全无法收到图片
