### ISSUE TITLE
最新版搭配GcmForMojo 小米推送无效

### ISSUE THREAD

**Issue by yesmiley** [sjdy521/Mojo-Webqq#245]
用旧版本可以，新版本推送一点反应都没有。
怀疑新版本冲突

**Comment by yeziaaa** [comment]
我说怎么最近怎么微信也收不到消息了？

**Comment by yeziaaa** [comment]
我这两天也没推送以为是Hwpush有问题，表示重装了一遍GCMFORMOJO又就可以推送了

**Comment by yeziaaa** [comment]
更新了mojoqq 重装了GFM表示可以正常推送了

**Comment by yesmiley** [comment]
其实你不用重装的 这两天好了 估计是mipush本身的问题






在 2018-07-03 19:19:16，"yeziaaa" <notifications@github.com> 写道：


更新了mojoqq 重装了GFM表示可以正常推送了
