### ISSUE TITLE
【群发冻结问题】如何可以防止冻结？ 反复冻结的后果时什么？

### ISSUE THREAD

**Issue by zenhox** [sjdy521/Mojo-Webqq#247]
今天用Mojo写了个群发的脚本，结果发了20多个群就冻结了，要修改密码？ 
然后我对脚本设置了睡眠间隔， 发送30来个群之后就又冻结了。
1： 如果这样反复东冻结最后会封号吗？
2： 有没有防止冻结的好办法！？

**Comment by sjdy521** [comment]
腾讯的脾气很难琢磨，你要自己慢慢研究 - -|
