### ISSUE TITLE
你好，mojo-webqq安装失败

### ISSUE THREAD

**Issue by wjz2001** [sjdy521/Mojo-Webqq#248]
日志显示
Connection error: IO::Socket::SSL 2.009+ required for TLS support at t/https.t line 17

Result: FAIL
Failed 1/2 test programs. 0/1 subtests failed.
Makefile:1173: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
-> FAIL Installing Mojo::Webqq failed. See /root/.cpanm/work/1531288398.3328/build.log for details. Retry with --force to force install it.

libssl-dev我已经安装好了，mojoqq也是用cpanm的方式安装的，请问这是怎么回事

**Comment by wjz2001** [comment]
完整日志

> cpanm (App::cpanminus) 1.7044 on perl 5.020002 built for i586-linux-gnu-thread-multi-64int
Work directory is /root/.cpanm/work/1531319018.3077
You have make /usr/bin/make
You have LWP 6.08
You have /bin/tar: tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Mojo::Webqq () on cpanmetadb ...
--> Working on Mojo::Webqq
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Webqq-2.2.2.tar.gz
-> OK
Unpacking Mojo-Webqq-2.2.2.tar.gz
Entering Mojo-Webqq-2.2.2
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
Configuring Mojo-Webqq-v2.2.2
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Mojo::Webqq
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Digest::MD5 0 ... Yes (2.53)
Checking if you have Compress::Raw::Zlib 0 ... Yes (2.065)
Checking if you have Time::HiRes 0 ... Yes (1.9726)
Checking if you have IO::Socket::SSL 1.94 ... Yes (2.002)
Checking if you have Time::Piece 0 ... Yes (1.27)
Checking if you have Encode::Locale 0 ... Yes (1.03)
Checking if you have IO::Compress::Gzip 0 ... Yes (2.064)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
Checking if you have Time::Seconds 0 ... Yes (1.27)
Checking if you have Digest::SHA 0 ... Yes (5.88)
Checking if you have Mojolicious 7.69 ... Yes (7.87)
Building and testing Mojo-Webqq-v2.2.2
cp lib/Mojo/Webqq/Client/Remote/_get_group_pic.pm blib/lib/Mojo/Webqq/Client/Remote/_get_group_pic.pm
cp lib/Mojo/Webqq/Client/Remote/_recv_message.pm blib/lib/Mojo/Webqq/Client/Remote/_recv_message.pm
cp lib/Mojo/Webqq/Counter.pm blib/lib/Mojo/Webqq/Counter.pm
cp lib/Mojo/Webqq/Discuss/Member.pm blib/lib/Mojo/Webqq/Discuss/Member.pm
cp lib/Mojo/Webqq/Client/Remote/_check_sig.pm blib/lib/Mojo/Webqq/Client/Remote/_check_sig.pm
cp lib/Mojo/Webqq/Message.pm blib/lib/Mojo/Webqq/Message.pm
cp lib/Mojo/Webqq.pod blib/lib/Mojo/Webqq.pod
cp lib/Mojo/Webqq/Base.pm blib/lib/Mojo/Webqq/Base.pm
cp lib/Mojo/Webqq/Client/Remote/logout.pm blib/lib/Mojo/Webqq/Client/Remote/logout.pm
cp lib/Mojo/Webqq/Client/Remote/_get_offpic.pm blib/lib/Mojo/Webqq/Client/Remote/_get_offpic.pm
cp lib/Mojo/Webqq/Client/Remote/_relink.pm blib/lib/Mojo/Webqq/Client/Remote/_relink.pm
cp lib/Mojo/Webqq/Group/Member.pm blib/lib/Mojo/Webqq/Group/Member.pm
cp lib/Mojo/Webqq/Client/Remote/change_state.pm blib/lib/Mojo/Webqq/Client/Remote/change_state.pm
cp lib/Mojo/Webqq/Client/Remote/_prepare_for_login.pm blib/lib/Mojo/Webqq/Client/Remote/_prepare_for_login.pm
cp lib/Mojo/Webqq/Client/Remote/_get_img_verify_code.pm blib/lib/Mojo/Webqq/Client/Remote/_get_img_verify_code.pm
cp lib/Mojo/Webqq/Client/Remote/_check_login.pm blib/lib/Mojo/Webqq/Client/Remote/_check_login.pm
cp lib/Mojo/Webqq/Log.pm blib/lib/Mojo/Webqq/Log.pm
cp lib/Mojo/Webqq/Client/Remote/_login1.pm blib/lib/Mojo/Webqq/Client/Remote/_login1.pm
cp lib/Mojo/Webqq/Client/Remote/_check_verify_code.pm blib/lib/Mojo/Webqq/Client/Remote/_check_verify_code.pm
cp lib/Mojo/Webqq/Group.pm blib/lib/Mojo/Webqq/Group.pm
cp lib/Mojo/Webqq/Friend.pm blib/lib/Mojo/Webqq/Friend.pm
cp lib/Mojo/Webqq/Client/Remote/_get_vfwebqq.pm blib/lib/Mojo/Webqq/Client/Remote/_get_vfwebqq.pm
cp lib/Mojo/Webqq/Message/Emoji.pm blib/lib/Mojo/Webqq/Message/Emoji.pm
cp lib/Mojo/Webqq/Controller.pm blib/lib/Mojo/Webqq/Controller.pm
cp lib/Mojo/Webqq.pm blib/lib/Mojo/Webqq.pm
cp lib/Mojo/Webqq/List.pm blib/lib/Mojo/Webqq/List.pm
cp lib/Mojo/Webqq/Discuss.pm blib/lib/Mojo/Webqq/Discuss.pm
cp lib/Mojo/Webqq/Client/Remote/_get_qrlogin_pic.pm blib/lib/Mojo/Webqq/Client/Remote/_get_qrlogin_pic.pm
cp lib/Mojo/Webqq/Client/Cron.pm blib/lib/Mojo/Webqq/Client/Cron.pm
cp lib/Mojo/Webqq/Client/Remote/_login2.pm blib/lib/Mojo/Webqq/Client/Remote/_login2.pm
cp lib/Mojo/Webqq/Client.pm blib/lib/Mojo/Webqq/Client.pm
cp lib/Mojo/Webqq/Cache.pm blib/lib/Mojo/Webqq/Cache.pm
cp lib/Mojo/Webqq/Message/Base.pm blib/lib/Mojo/Webqq/Message/Base.pm
cp lib/Mojo/Webqq/Client/Remote/_cookie_proxy.pm blib/lib/Mojo/Webqq/Client/Remote/_cookie_proxy.pm
cp lib/Mojo/Webqq/Model/Remote/_invite_friend.pm blib/lib/Mojo/Webqq/Model/Remote/_invite_friend.pm
cp lib/Mojo/Webqq/Model/Remote/_get_user_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_user_info.pm
cp lib/Mojo/Webqq/Model/Remote/_get_group_info_ext.pm blib/lib/Mojo/Webqq/Model/Remote/_get_group_info_ext.pm
cp lib/Mojo/Webqq/Model.pm blib/lib/Mojo/Webqq/Model.pm
cp lib/Mojo/Webqq/Model/Base.pm blib/lib/Mojo/Webqq/Model/Base.pm
cp lib/Mojo/Webqq/Model/Remote/_get_friend_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_friend_info.pm
cp lib/Mojo/Webqq/Model/Remote/_get_discuss_list_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_discuss_list_info.pm
cp lib/Mojo/Webqq/Model/Remote/_get_group_list_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_group_list_info.pm
cp lib/Mojo/Webqq/Message/Remote/_get_sess_sig.pm blib/lib/Mojo/Webqq/Message/Remote/_get_sess_sig.pm
cp lib/Mojo/Webqq/Message/Remote/_send_sess_message.pm blib/lib/Mojo/Webqq/Message/Remote/_send_sess_message.pm
cp lib/Mojo/Webqq/Model/Remote/_get_group_info_ext2.pm blib/lib/Mojo/Webqq/Model/Remote/_get_group_info_ext2.pm
cp lib/Mojo/Webqq/Model/Remote/_get_group_list_info_ext.pm blib/lib/Mojo/Webqq/Model/Remote/_get_group_list_info_ext.pm
cp lib/Mojo/Webqq/Message/Remote/_send_discuss_message.pm blib/lib/Mojo/Webqq/Message/Remote/_send_discuss_message.pm
cp lib/Mojo/Webqq/Model/Ext.pm blib/lib/Mojo/Webqq/Model/Ext.pm
cp lib/Mojo/Webqq/Model/Remote/_get_group_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_group_info.pm
cp lib/Mojo/Webqq/Message/Remote/_send_friend_message.pm blib/lib/Mojo/Webqq/Message/Remote/_send_friend_message.pm
cp lib/Mojo/Webqq/Model/Remote/_get_user_friends_ext.pm blib/lib/Mojo/Webqq/Model/Remote/_get_user_friends_ext.pm
cp lib/Mojo/Webqq/Message/Handle.pm blib/lib/Mojo/Webqq/Message/Handle.pm
cp lib/Mojo/Webqq/Model/Remote/_get_friends_state.pm blib/lib/Mojo/Webqq/Model/Remote/_get_friends_state.pm
cp lib/Mojo/Webqq/Model/Remote/_get_recent_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_recent_info.pm
cp lib/Mojo/Webqq/Message/XMLescape.pm blib/lib/Mojo/Webqq/Message/XMLescape.pm
cp lib/Mojo/Webqq/Model/Remote/_get_user_friends.pm blib/lib/Mojo/Webqq/Model/Remote/_get_user_friends.pm
cp lib/Mojo/Webqq/Model/Remote/_get_discuss_info.pm blib/lib/Mojo/Webqq/Model/Remote/_get_discuss_info.pm
cp lib/Mojo/Webqq/Message/Remote/_send_group_message.pm blib/lib/Mojo/Webqq/Message/Remote/_send_group_message.pm
cp lib/Mojo/Webqq/Message/Face.pm blib/lib/Mojo/Webqq/Message/Face.pm
cp lib/Mojo/Webqq/Message/Queue.pm blib/lib/Mojo/Webqq/Message/Queue.pm
cp lib/Mojo/Webqq/Model/Remote/_kick_group_member.pm blib/lib/Mojo/Webqq/Model/Remote/_kick_group_member.pm
cp lib/Mojo/Webqq/Plugin/Pu.pm blib/lib/Mojo/Webqq/Plugin/Pu.pm
cp lib/Mojo/Webqq/Plugin/PostQRcode.pm blib/lib/Mojo/Webqq/Plugin/PostQRcode.pm
cp lib/Mojo/Webqq/Plugin/GCM.pm blib/lib/Mojo/Webqq/Plugin/GCM.pm
cp lib/Mojo/Webqq/Plugin/PostQRcodeToTelegram.pm blib/lib/Mojo/Webqq/Plugin/PostQRcodeToTelegram.pm
cp lib/Mojo/Webqq/Model/Remote/get_single_long_nick.pm blib/lib/Mojo/Webqq/Model/Remote/get_single_long_nick.pm
cp lib/Mojo/Webqq/Plugin/PostImgVerifycode.pm blib/lib/Mojo/Webqq/Plugin/PostImgVerifycode.pm
cp lib/Mojo/Webqq/Plugin/KnowledgeBase.pm blib/lib/Mojo/Webqq/Plugin/KnowledgeBase.pm
cp lib/Mojo/Webqq/Plugin/Riddle.pm blib/lib/Mojo/Webqq/Plugin/Riddle.pm
cp lib/Mojo/Webqq/Model/Remote/_set_group_admin.pm blib/lib/Mojo/Webqq/Model/Remote/_set_group_admin.pm
cp lib/Mojo/Webqq/Model/Remote/get_qq_from_id.pm blib/lib/Mojo/Webqq/Model/Remote/get_qq_from_id.pm
cp lib/Mojo/Webqq/Plugin/Perldoc.pm blib/lib/Mojo/Webqq/Plugin/Perldoc.pm
cp lib/Mojo/Webqq/Plugin/RikkaGCM.pm blib/lib/Mojo/Webqq/Plugin/RikkaGCM.pm
cp lib/Mojo/Webqq/Plugin/Qiandao.pm blib/lib/Mojo/Webqq/Plugin/Qiandao.pm
cp lib/Mojo/Webqq/Model/Remote/_set_group_member_card.pm blib/lib/Mojo/Webqq/Model/Remote/_set_group_member_card.pm
cp lib/Mojo/Webqq/Plugin/FuckAndroid.pm blib/lib/Mojo/Webqq/Plugin/FuckAndroid.pm
cp lib/Mojo/Webqq/Plugin/MobileInfo.pm blib/lib/Mojo/Webqq/Plugin/MobileInfo.pm
cp lib/Mojo/Webqq/Plugin/IRCShell.pm blib/lib/Mojo/Webqq/Plugin/IRCShell.pm
cp lib/Mojo/Webqq/Plugin/HwPush.pm blib/lib/Mojo/Webqq/Plugin/HwPush.pm
cp lib/Mojo/Webqq/Model/Remote/_shutup_group_member.pm blib/lib/Mojo/Webqq/Model/Remote/_shutup_group_member.pm
cp lib/Mojo/Webqq/Plugin/Openqq.pm blib/lib/Mojo/Webqq/Plugin/Openqq.pm
cp lib/Mojo/Webqq/Plugin.pm blib/lib/Mojo/Webqq/Plugin.pm
cp lib/Mojo/Webqq/Plugin/ProgramCode.pm blib/lib/Mojo/Webqq/Plugin/ProgramCode.pm
cp lib/Mojo/Webqq/Plugin/MiPush.pm blib/lib/Mojo/Webqq/Plugin/MiPush.pm
cp lib/Mojo/Webqq/Plugin/LCMD.pm blib/lib/Mojo/Webqq/Plugin/LCMD.pm
cp lib/Mojo/Webqq/Plugin/GroupManage.pm blib/lib/Mojo/Webqq/Plugin/GroupManage.pm
cp lib/Mojo/Webqq/Plugin/Perlcode.pm blib/lib/Mojo/Webqq/Plugin/Perlcode.pm
cp lib/Mojo/Webqq/Plugin/IPwhere.pm blib/lib/Mojo/Webqq/Plugin/IPwhere.pm
cp lib/Mojo/Webqq/Plugin/FuckDaShen.pm blib/lib/Mojo/Webqq/Plugin/FuckDaShen.pm
cp lib/Mojo/Webqq/Model/Remote/_remove_group_admin.pm blib/lib/Mojo/Webqq/Model/Remote/_remove_group_admin.pm
cp lib/Mojo/Webqq/Plugin/GasPrice.pm blib/lib/Mojo/Webqq/Plugin/GasPrice.pm
cp lib/Mojo/Webqq/Plugin/FmPush.pm blib/lib/Mojo/Webqq/Plugin/FmPush.pm
cp lib/Mojo/Webqq/Model/Remote/_qiandao.pm blib/lib/Mojo/Webqq/Model/Remote/_qiandao.pm
cp lib/Mojo/Webqq/Server.pm blib/lib/Mojo/Webqq/Server.pm
cp lib/Mojo/Webqq/Plugin/StockInfo.pm blib/lib/Mojo/Webqq/Plugin/StockInfo.pm
cp lib/Mojo/Webqq/User.pm blib/lib/Mojo/Webqq/User.pm
cp lib/Mojo/Webqq/Plugin/UploadQRcode2.pm blib/lib/Mojo/Webqq/Plugin/UploadQRcode2.pm
cp lib/Mojo/Webqq/Recent/Group.pm blib/lib/Mojo/Webqq/Recent/Group.pm
cp lib/Mojo/Webqq/Run.pm blib/lib/Mojo/Webqq/Run.pm
cp lib/Mojo/Webqq/Request.pm blib/lib/Mojo/Webqq/Request.pm
cp lib/Mojo/Webqq/Plugin/ShowQRcode.pm blib/lib/Mojo/Webqq/Plugin/ShowQRcode.pm
cp lib/Mojo/Webqq/Plugin/Translation.pm blib/lib/Mojo/Webqq/Plugin/Translation.pm
cp lib/Mojo/Webqq/Recent/Friend.pm blib/lib/Mojo/Webqq/Recent/Friend.pm
cp lib/Mojo/Webqq/Plugin/UploadQRcode.pm blib/lib/Mojo/Webqq/Plugin/UploadQRcode.pm
cp lib/Mojo/Webqq/Plugin/ZiYue.pm blib/lib/Mojo/Webqq/Plugin/ZiYue.pm
cp lib/Mojo/Webqq/Recent/Discuss.pm blib/lib/Mojo/Webqq/Recent/Discuss.pm
cp lib/Mojo/Webqq/Util.pm blib/lib/Mojo/Webqq/Util.pm
cp lib/Mojo/Webqq/Plugin/ShowMsg.pm blib/lib/Mojo/Webqq/Plugin/ShowMsg.pm
cp lib/Mojo/Webqq/Plugin/SmartReply.pm blib/lib/Mojo/Webqq/Plugin/SmartReply.pm
Manifying blib/man3/Mojo::Webqq.3pm
Manifying blib/man3/Mojo::Webqq::Plugin::IPwhere.3pm
Manifying blib/man3/Mojo::Webqq::Plugin::ProgramCode.3pm
PERL_DL_NONLAZY=1 PERL_USE_UNSAFE_INC=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Connection error: IO::Socket::SSL 2.009+ required for TLS support at t/https.t line 17.
# Looks like your test exited with 255 before it could output anything.
t/https.t ........ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
t/load_module.t .. ok

Test Summary Report
-------------------
t/https.t      (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 1 tests but ran 0.
Files=2, Tests=1,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.49 cusr  0.03 csys =  0.53 CPU)
Result: FAIL
Failed 1/2 test programs. 0/1 subtests failed.
Makefile:1173: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
-> FAIL Installing Mojo::Webqq failed. See /root/.cpanm/work/1531319018.3077/build.log for details. Retry with --force to force install it.

**Comment by sjdy521** [comment]
先执行下 cpanm IO::Socket::SSL 然后再重新安装Mojo::Webqq
