### ISSUE TITLE
openqq插件的改进意见

### ISSUE THREAD

**Issue by snail007** [sjdy521/Mojo-Webqq#25]
目前各种post到外部api地址的json消息里面不包含发送者qq号或者接收者qq号，群号码，这样外部程序很难对消息进行下一步的判断和操作，建议加上这些信息。

**Comment by sjdy521** [comment]
已经支持
> {"receiver":"......","msg_time":"1456479382","content":"test","msg_class":"recv","gnumber":123456,"sender_id":"1234564","receiver_id":"1231245","group":"IT......","group_id":"1313131","receiver_qq":1313131,"sender":".........","msg_id":"4324","sender_qq":21213,"type":"group_message"}
