### ISSUE TITLE
华为push收不到推送

### ISSUE THREAD

**Issue by kettly1260** [sjdy521/Mojo-Webqq#260]
之前一直能收到推送，就是从前几天开始华为推送就用不了了，用的是华为的手机，内置推送，而且设备码就算系统重置、重装APP都没有变过。但是已经无法收到推送，其它软件的推送是正常的
服务端未提示任何问题，且GCM可以正常推送

**Comment by kettly1260** [comment]
时隔多天自己又突然能退送了
猜测是华为的服务器出问题的

**Comment by sjdy521** [comment]
应该是网络不稳定问题
