### ISSUE TITLE
服务端运行后提示Mojo::Transaction错误

### ISSUE THREAD

**Issue by sakuyamaij** [sjdy521/Mojo-Webqq#262]
以前在CentOS上跑的好好的，现在往Ubuntu迁移时重新安装遇到这么一个问题，网上没有搜到相关资料。请问到底是怎么回事。
姑且客户端可以连上并正常扫码登陆运行。就是这个错误一直刷屏，不知道问题出在哪

![Snipaste_2018-10-07_17-48-51.jpg](https://i.loli.net/2018/10/07/5bb9d68d2defd.jpg)

**Comment by sjdy521** [comment]
@sakuyamaij 项目有依赖了一个第三方的模块 叫 Mojolicious
这个模块的版本也一直在升级，使用到了它的一些旧的代码所以报这种警告了
可以卸载掉高版本的Mojolicious 安装指定低版本就可以解决，操作如下：

```
cpanm  -U Mojolicious ;
cpanm https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.69.tar.gz ;

```

**Comment by sakuyamaij** [comment]
谢谢解答，既然对运行没有妨碍那就不去管它了
