### ISSUE TITLE
http api check_event有时候会返回[null]

### ISSUE THREAD

**Issue by sym233** [sjdy521/Mojo-Webqq#264]
似乎是有多个请求check_event时会这样，不确定

**Comment by sjdy521** [comment]
有可能塞进消息队列里的event对象本身由于某种bug变成了null，能从返回结果里把这种情况过滤掉吗

**Comment by sym233** [comment]
能吧

**Comment by sym233** [comment]
顺便问一下，发送消息的频率有限制吗

**Comment by sjdy521** [comment]
官方对这个有限制，程序全局也限制了每隔3s发一条消息，建议不要太频繁调用，尽量按照正常人聊天的频率
