### ISSUE TITLE
在不同系统下接收到的消息换行出错的问题和<?引起的问题

### ISSUE THREAD

**Issue by ajacker** [sjdy521/Mojo-Webqq#266]
电脑下
![tim 20181024150926](https://user-images.githubusercontent.com/32221656/47412639-d7324280-d79e-11e8-9206-057bcc3fe538.png)
安卓手机下
![2 xvp5yakb2 66dt8 30 fg](https://user-images.githubusercontent.com/32221656/47412718-12347600-d79f-11e8-97e2-a41327cf3ac1.png)
苹果系统下（可能是因为换行引起的？但是未能复现这个bug，不知道具体是哪几个字符）
![sit nj i mhohapr3kgc](https://user-images.githubusercontent.com/32221656/47413005-b7e7e500-d79f-11e8-8793-25d139ddaea4.png)
标题上那两个特殊字符引起的问题（不分系统）（我发现markdown以这个开头后面的也无法正常显示）
![8r34wf l7duvko0 4 s6](https://user-images.githubusercontent.com/32221656/47413216-45c3d000-d7a0-11e8-9ca5-c3bed6c7092b.jpg)
![j8ncx2dv1z 74 0o9kdk2_v](https://user-images.githubusercontent.com/32221656/47413107-05645200-d7a0-11e8-997a-3d1b4bc1cceb.png)

**Comment by ajacker** [comment]
<?引起的问题（不分系统）
![8r34wf l7duvko0 4 s6](https://user-images.githubusercontent.com/32221656/47413216-45c3d000-d7a0-11e8-9ca5-c3bed6c7092b.jpg)
![j8ncx2dv1z 74 0o9kdk2_v](https://user-images.githubusercontent.com/32221656/47413107-05645200-d7a0-11e8-997a-3d1b4bc1cceb.png)

**Comment by bollwarm** [comment]
那个报错是，因为mojo架构升级，你新安装用的最新版本有兼容性问题。安装老版本mojo就ok，等后续兼容。

<?开头的消息有问题的话，用户html转码发试试

**Comment by sjdy521** [comment]
网页版qq的自身问题，来自不同设备的内容，换行符有时候丢掉了，不是程序的问题，这个暂时没办法
