### ISSUE TITLE
response return curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by Oly-Don** [sjdy521/Mojo-Webqq#269]
接口: /openqq/send_friend_message

调用方式:curl -H "Contect-Type:application/x-www-form-urlencoded" http://127.0.0.1:5000/openqq/send_friend_message?id=612321&content=hello

问题:
返回curl: (52) Empty reply from server

[1]+  Exit 52

**Comment by sjdy521** [comment]
url加上引号
