### ISSUE TITLE
IRCShell插件更换监听地址

### ISSUE THREAD

**Issue by MaskRay** [sjdy521/Mojo-Webqq#27]
似乎`listen`得用array形式而不能用`data=>{listen=>{host=>'127.0.0.1',port=>6668}}'`
文档 https://metacpan.org/pod/distribution/Mojo-Webqq/doc/Webqq.pod 中也要修正

```bash
perl -MMojo::Webqq -e 'Mojo::Webqq->new(qq=>xxxxxxxx)->login->load("ShowMsg")->load("IRCShell",data=>{listen=>[{host=>'127.0.0.1',port=>6668}]})->run()'
```

**Comment by MaskRay** [comment]
```
load_friend         #0|1 默认是1 是否初始为每个好友生成irc虚拟帐号并加入频道 #我的好友
```
似乎默认是0

**Comment by sjdy521** [comment]
哈哈 多谢帮忙找到了这么多问题 我会一一完善下 可以比较下irc使用体验方面有没有什么借鉴之处 我这个irc自己也是用了蛮久的 但真正其他感兴趣用起来的人寥寥无几


发自 网易邮箱大师
在2016年03月05日 11:00，Ray Song 写道:
load_friend         #0|1 默认是1 是否初始为每个好友生成irc虚拟帐号并加入频道 #我的好友


似乎默认是0

**Comment by MaskRay** [comment]
wechatircd的做法是：

连接IRC server后自动加入 +status (类似于 IRCShell 的 #我的好友)，里面显示朋友列表

“程序默认选项为--join auto，收到某个微信群的第一条消息后会自动加入对应的channel，即开始接收该微信群的消息。”
--ignore 选项设置不自动加入的channel名

/list 可用于显示有哪些频道


然后创建 ~/.config/systemd/user/wechatircd.service
```
[Unit]
Description=wechatircd
Documentation=https://github.com/MaskRay/wechatircd

[Service]
WorkingDirectory=%h/projects/wechatircd
ExecStart=/home/ray/projects/wechatircd/wechatircd.py --tls-key a.key --tls-cert a.crt --password a --ignore 不想自动加入的群名称 不想自动加入的群名称2

[Install]
WantedBy=default.target
```
让它自动启动

**Comment by sjdy521** [comment]
listen要用数组的形式是为了支持绑定多个端口，因为之前发现有些网络6667端口会被封
文档已经修改了
```
listen=>[ 
    {host=>"127.0.0.1",port=>6667}, 
    {host=>"127.0.0.1",port=>6668}, 
]
```
```load_friend => 0 ```默认值是1 这个也已经文档修正了
因为考虑到好友数量通常比较多，一次性全部加入 #我的好友 频道中没必要，只有对好友聊天，就会自动加入到对应的频道了

看你描述的 你的ircd的做法和我当前的很相似 :-)
