### ISSUE TITLE
退出之后不清理cookie && 增加配置文件

### ISSUE THREAD

**Issue by sunmingyang** [sjdy521/Mojo-Webqq#270]
我不会perl代码..在尝试解决退出不清理cookie的时候,发现 lib/Mojo/Webqq.pm 里面有 allow_message_sync 这个设置.如果不看代码是不会知道的..所以能不能劳烦把这些配置统一放在配置文件内,来自行配置呢?

退出清理cookie我不确定是否是退出Mojo就清理了.不过每次网络不好的时候,都需要重新扫码登陆其实是挺烦人的...不知道能不能提炼成配置或者其他的方式,来保存这个状态,不要因为网络闪断而频繁扫码...

抱歉,我们公司的网络特别特别的差劲..

**Comment by bollwarm** [comment]
webqq官方有定期重启机制，天肯定会断，必须重新扫，这是腾讯服务器端限制的，没法突破。

**Comment by sjdy521** [comment]
@sunmingyang 单独的配置文件，这个后续考虑下，有精力会支持下
目前所有的参数可以参考开发文档 https://metacpan.org/pod/distribution/Mojo-Webqq/doc/Webqq.pod#new()

程序本身是有自动保存cookie方便下次直接面扫码登录的，以前是可以正常工作，但是最近官方的webqq各种问题，已经没办法复用cookie来避免频繁扫码了，这个是webqq官方的问题，暂时无解
