### ISSUE TITLE
post api插件bug

### ISSUE THREAD

**Issue by snail007** [sjdy521/Mojo-Webqq#28]
我发现一个问题 腾讯新闻会主动推新闻给机器人，机器人收到的是一堆xml

**Comment by sjdy521** [comment]
目前没有对公众号进行特殊区分，都被视作好友，发送的xml格式消息没有做特殊处理，后续会进行完善

**Comment by sjdy521** [comment]
move to https://github.com/sjdy521/Mojo-Weixin/issues/11
