### ISSUE TITLE
关于使用api发送信息不定时延迟的问题

### ISSUE THREAD

**Issue by chenshenwei1998** [sjdy521/Mojo-Webqq#280]
首先感谢作者的webqq框架，很好用，但是我发现用api发送信息会出现不定时延迟，比如用最简单的python语句运行：
`response = requests.post("http://127.0.0.1:5000/openqq/send_group_message", data={'id': '629342528', 'content': 'what are you doing?'})`
不断运行以上语句，大部分时候可以立刻发送信息，但仍有很多时候会出现raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response的报错，但是信息仍然可以发送，只是有延迟（几十秒甚至几分钟），在这种情况下发送的信息的顺序也会出现错乱，请问一下是什么原因呢？感谢！

**Comment by sjdy521** [comment]
重要通知：WebQQ将在2019年1月1日停止服务，此项目目前已停止维护，感谢大家四年来的一路陪伴
