### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by mrhoric** [sjdy521/Mojo-Webqq#3]
你好
我在看你的这个基于webqq的qq机器人时看到有个智能回复的模块，里面有个可以@群人员的语句，但是我不懂Perl，能不能给我讲讲呢？麻烦了

$input=~s/\@\Q$user_nick\E ?|\[[^\[\]]+\]\x01|\[[^\[\]]+\]//g;

**Comment by sjdy521** [comment]
这句代码注意是把消息内容中包含“@xxx”或者消息内容中包含的图片或表情等字符串去掉 再将处理后的内容调用智能回复api，因为智能回复的api是不会理解qq里的艾特 或者理解一些特殊的表情的

**Comment by sjdy521** [comment]
不懂perl没关系 或者你有什么样的需求可以先提出来 再考虑用什么样的形式来满足你

**Comment by mrhoric** [comment]
我是想能让机器人@人，但是webqq上面没有这接口，只能网上满天的找怎么@，但是都没有，看这个有点像，但是还是不是的，webqq真的不能@人么

**Comment by sjdy521** [comment]
基于web的qq，你直接去w.qq.com亲自使用下就知道哪些功能有 哪些功能做不到了 确实不支持客户端的艾特功能

**Comment by mrhoric** [comment]
w.qq.com上面现在几乎没什么功能了，群管理这些全是靠着找那些老的残留的接口弄的

**Comment by sjdy521** [comment]
群管理 用qun.qq.com是否可以

**Comment by mrhoric** [comment]
那用的不是同一个cookie了，要重新授权，听说是可以转换cookie，感觉太麻烦了，原来的留的老接口挺好用的，这几天看这些老接口不知道看了多少种语言，抓了多少包。。。

**Comment by sjdy521** [comment]
建议别用什么老接口了，腾讯让你用smartqq 你就只能用smartqq，没有的开放的功能，用老接口指不定哪天就关闭了，如果真希望使用这些功能可以研究下客户端协议，qun.qq.com虽然不同cookie但并不影响什么，想用的话总是可以拿来用 只是稍微绕了一下而已

**Comment by sjdy521** [comment]
@mrhoric 老接口可以批量获取qq号吗

**Comment by mrhoric** [comment]
你是说把uin转qq号么，没有的

**Comment by sjdy521** [comment]
我现在封装了一套自己对外的发送消息api，但如果通过uin指定发送对象，uin会经常变动
一个个获取uin对应的qq，又要查询很多次，效率也不行，还担心有查询次数限制

**Comment by mrhoric** [comment]
我是觉得uin这玩意特蛋疼，怎么不直接用qq帐号

**Comment by mrhoric** [comment]
你api接口用qq号啊，uin转qq让用户自己做，我看github上别人是自己建立个小数据库，转一次就存字典中

**Comment by sjdy521** [comment]
uin每次登陆都可能变动，查询可以做缓存，但下次再登陆就没有意义了

**Comment by mrhoric** [comment]
对啊，就是做缓存用

**Comment by gitlsl** [comment]
你好，这个项目有交流群吗？ 我是用c#开发程序的， 想怎么接入你这个程序实现机器人功能，好像是用远程api 走 本地http 吗

**Comment by sjdy521** [comment]
可以把qq号发到我邮箱，我加你一下，或者直接来我的在线聊天室：http://irc.perfi.wang/

**Comment by sjdy521** [comment]
@gitlsl v1.4.7版本的Openqq插件支持设置接收消息的上报接口，希望对你有帮助

    接收消息上报接口示例：
    $client->load("Openqq",data=>{
        listen => [{host=>xxx,port=>xxx}],
        post_api=> 'http://127.0.0.1/post_api',
    });

    接收到消息后，插件会通过HTTP POST请求的方式将json格式的消息上报到http://127.0.0.1:3000/post_api
    
    connect to 127.0.0.1 port 3000    
    POST /post_api
    
    {   "receiver":"小灰",
        "msg_time":"1442542632",
        "content":"测试一下",
        "msg_class":"recv",
        "sender_id":"2372835507",
        "receiver_id":"4072574066",
        "group":"PERL学习交流",
        "group_id":"2617047292",
        "sender":"灰灰",
        "msg_id":"10856",
        "type":"group_message"
    }
    
    支持好友消息、群消息、讨论组消息、临时消息的上报

**Comment by gitlsl** [comment]
@sjdy521   好的 我试试  这程序能在win7 下跑吗   我下载安装了了 Strawberry  然后 运行 makefile    ， demo 还是跑不起来  好像是说少了  Webqq::Encryption  ？

**Comment by sjdy521** [comment]
建议使用cpan或者cpanm在线安装，自动解决依赖问题
另外windows下建议尽量使用cygwin类linux环境使用perl

发自 网易邮箱大师
在2015年09月18日 21:29，gitlsl 写道:

@sjdy521 好的 我试试 这程序能在win7 下跑吗 我下载安装了了 Strawberry 然后 运行 makefile ， demo 还是跑不起来 好像是说少了 Webqq::Encryption ？

**Comment by sjdy521** [comment]
提示少了Webqq::Encryption 模块也可以手动安装下

发自 网易邮箱大师
在2015年09月18日 21:29，gitlsl 写道:

@sjdy521 好的 我试试 这程序能在win7 下跑吗 我下载安装了了 Strawberry 然后 运行 makefile ， demo 还是跑不起来 好像是说少了 Webqq::Encryption ？

**Comment by sjdy521** [comment]
@mrhoric 目前测试发现，登录了smartqq之后，qun.qq.com就不需要再重新登录了，也就是说smartqq的登录cookie是可以共享给qun.qq.com的，大概看了下js代码，主要是skey和pt_uin两个cookie，用这个做群管理还是挺方便的
