### ISSUE TITLE
代理网络下安装webqq失败。

### ISSUE THREAD

**Issue by linux0ne** [sjdy521/Mojo-Webqq#36]
$sudo cpanm --mirror http://mirrors.163.com/cpan/ Mojo::Webqq
[sudo] cymode 的密码： 
--> Working on Mojo::Webqq
Fetching http://mirrors.163.com/cpan/authors/id/S/SJ/SJDY/Mojo-Webqq-1.8.3.tar.gz ... OK
Configuring Mojo-Webqq-v1.8.3 ... OK
Building and testing Mojo-Webqq-v1.8.3 ... FAIL
! Installing Mojo::Webqq failed. See /home/cymode/.cpanm/work/1469589269.17526/build.log for details. Retry with --force to force install it.

下面是log的内容

http://paste.ubuntu.com/21097102/

**Comment by linux0ne** [comment]
我的网络类型是局域网，通过局域网内的一个IP作代理，然后连接外网……

**Comment by sjdy521** [comment]
从你的日志上来看

模块已经下载成功，已经编译成功，但是在make test的时候报错：

> Connection error: No route to host at t/https.t line 16.
> # Looks like your test exited with 113 before it could output anything.
> t/https.t ........ 

也就是在你本地网络访问这个url的时候报错：No route to host

> https://ui.ptlogin2.qq.com/cgi-bin/login?daid=164&target=self&style=16&mibao_css=m_webqq&appid=501004106&enable_qlogin=0&no_verifyimg=1&s_url=http%3A%2F%2Fw.qq.com%2Fproxy.html&f_url=loginerroralert&strong_login=1&login_state=10&t=20131024001

你自身网络的问题

**Comment by linux0ne** [comment]
@sjdy521 
我将上方的地址放到浏览器中去访问，是可以正常访问的呀。它自动转到了下面的地址处：

ui.ptlogin2.qq.com/cgi-bin/login

总体来说我现在该怎么办呢？
http or https类型的网络我通过代理都可以访问的。

**Comment by sjdy521** [comment]
加qq或者其他方式我帮你远程看下？

**Comment by linux0ne** [comment]
@sjdy521 
现在在ubuntu 下， 远程估计是不行吧？  
我的QQ是3131489789。
或者linux下有什么好的教程方式可以教教我？  
qtox 可以么？
qtox号码 ：qtox0noffice@utox.org
需要手机号的话，可以加QQ或qtox后我告诉你，视频通话也可以。

**Comment by linux0ne** [comment]
该问题已得到开发者的有利解决，代码已更新，可关闭本帖。

**Comment by sjdy521** [comment]
问题已经确定，是由于系统设置了http/https代理才能够上网，直接对外请求不通
已经支持自动检测系统代理设置
