### ISSUE TITLE
openQQ发送群消息请求成功, 但实际没有发出去

### ISSUE THREAD

**Issue by fantasymaker-cn** [sjdy521/Mojo-Webqq#37]
使用openQQ发送群消息, POST JSON格式数据:

```
http://127.0.0.1:5000/openqq/send_group_message

{
   "gnumber":1234,
   "content":text
}
```

收到成功响应:
```
200
{ code: 0, msg_id: 73300027, status: '发送成功' }
```

但是消息实际并没有发出去.

而发送好友消息, 用`http://127.0.0.1:5000/openqq/send_message` POST + JSON可以发送到.

请问是哪里不对?

**Comment by sjdy521** [comment]
如Q上沟通的情况，发送消息使用的是application/x-www-form-urlencoded格式而非JSON格式，问题已经解决
