### ISSUE TITLE
能否增加点歌和定时发送消息功能

### ISSUE THREAD

**Issue by moboard** [sjdy521/Mojo-Webqq#38]
先感谢灰灰为我们提供了这个非常不错的QQ文案。
提两个建议，灰灰酌情看能不能采纳实现：
1. QQ里有个“音乐”功能，可不可以实现这个功能呢？通过指令点歌，原版qq可以在窗口里插放，linux及其它的给一个音视频链接，用户决定是不是要调用外部播放器播放。
2. 定时发送消息到不同群或者不同好友。这个可以用来商用，发广告（当然得有限制）。

**Comment by sjdy521** [comment]
这两点功能当前都可以实现，这是常规的发送消息和接收消息，点歌只能给出一个链接，无法实现qq窗口内播放


你是一个开发者还是只是一个普通用户？
如果你是一个开发者，可以借助已经提供的api接口来二次开发实现你想要的这两点


发自网易邮箱大师
在2016年10月05日 10:12，moboard 写道:

先感谢灰灰为我们提供了这个非常不错的QQ文案。
提两个建议，灰灰酌情看能不能采纳实现：

QQ里有个“音乐”功能，可不可以实现这个功能呢？通过指令点歌，原版qq可以在窗口里插放，linux及其它的给一个音视频链接，用户决定是不是要调用外部播放器播放。
定时发送消息到不同群或者不同好友。这个可以用来商用，发广告（当然得有限制）。

**Comment by moboard** [comment]
我是普通用户。
如果是QQ播放器能识别出来的就好了。按说QQ音乐、网易云音乐、虾米、百度音乐什么的应该有开放的API的。

**Comment by sjdy521** [comment]
我可以找找qq音乐有没有开放api


定时发送消息到指定的群，这个几行代码就可以完成 有需要可以把你详细的需求描述下 我帮忙实现一下 你只需要把代码复制黏贴过去运行就行了


发自网易邮箱大师
在2016年10月05日 11:23，moboard 写道:

我是普通用户。
如果是QQ播放器能识别出来的就好了。按说QQ音乐、网易云音乐、虾米、百度音乐什么的应该有开放的API的。

**Comment by moboard** [comment]
点歌模仿实现QQ的歌曲功能：
点歌 歌曲名  #点歌给自己不指定歌手演唱，可能是原唱，也可能是随机同名的歌曲
点歌 歌曲名 歌手名 #点歌给自己，指定歌手名 #指定歌手名演唱的版本
点歌 @用户 歌曲名  #点歌给指定用户，不指定歌手演唱，可能是原唱，也可能是随机同名的歌曲
点歌 @用户 歌曲名  歌手名 #点歌给指定用户，指定歌手名 #指定歌手名演唱的版本

查了下，目前虾米和网易云音乐都没有开放API，不过有人弄出来了一些：
虾米/网易云音乐API接口  https://lophita.com/xiami-music-api.html
网易云音乐无线音箱系统 https://github.com/grasses/NetEase-Wireless-MusicBox
网易云音乐常用API浅析 http://moonlib.com/606.html


定时发送消息：
1、随机时间（时间、频率自己可定义）给群发送消息，内容可以是本地文本，也可以是无意义的打招呼。（可指发给定群、好友/指定分组好友，或者黑名单之外的都可以接受到消息。）
 
2、定时发送消息到群，或者是指定用户，内容可以是本地文本，也可以是无意义的打招呼。（可指发给定群、好友/指定分组好友，或者黑名单之外的都可以接受到消息。）
3、群主可发送@全体的群公告。

最好是发出指令后执行，比如：
 群发  消息内容

**Comment by moboard** [comment]
有几个基于py的网易云音乐项目你看看有没有借鉴作用
https://github.com/darknessomi/musicbox  #近几天还有更新，比较活跃
https://github.com/bluetomlee/NetEase-MusicBox   #两年前最后更新的

**Comment by moboard** [comment]
有点汗，我发现有一个项目有群发消息的功能……

**Comment by sjdy521** [comment]
群发消息是这种项目最基本的功能呀…


发自网易邮箱大师
在2016年10月05日 22:13，moboard 写道:

有点汗，我发现有一个项目有群发消息的功能……
