### ISSUE TITLE
登录脚本报错了

### ISSUE THREAD

**Issue by zjcnew** [sjdy521/Mojo-Webqq#42]
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate Mojo/Webqq.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./run.pl line 2.
BEGIN failed--compilation aborted at ./run.pl line 2.

**Comment by sjdy521** [comment]
看起来是因为你没有成功安装 Mojo::Webqq
是否有按照README文档里的安装步骤使用cpanm成功安装呢？

**Comment by zjcnew** [comment]
重新安装成功了，但是运行登录脚本报错，为什么？
Can't locate Mojo/Webqq.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./a.pl line 2.
BEGIN failed--compilation aborted at ./a.pl line 2.

**Comment by sjdy521** [comment]
加Q群讨论吧 498880156

**Comment by sjdy521** [comment]
看起来是因为你没有成功安装 Mojo::Webqq
是否有按照README文档里的安装步骤使用cpanm成功安装呢？


发自网易邮箱大师
在2016年10月24日 17:31，zjcnew 写道:

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = (unset),
LANG = "en_US.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Can't locate Mojo/Webqq.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./run.pl line 2.
BEGIN failed--compilation aborted at ./run.pl line 2.

**Comment by shibeta** [comment]
同样遇到这个问题
安装时
`[root@vultr ~]# cpanm Mojo::Webqq --force
--> Working on Mojo::Webqq
Fetching http://www.cpan.org/authors/id/S/SJ/SJDY/Mojo-Webqq-2.2.3.tar.gz ... OK
Configuring Mojo-Webqq-v2.2.3 ... OK
Building and testing Mojo-Webqq-v2.2.3 ... FAIL
! Testing Mojo-Webqq-v2.2.3 failed but installing it anyway.
Successfully reinstalled Mojo-Webqq-v2.2.3
`
结果就是
`[root@vultr ~]# perl GCM.pl
Can't locate Mojo/EventEmitter.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/share/perl5/Mojo/Webqq/Base.pm line 75.
BEGIN failed--compilation aborted at /usr/local/share/perl5/Mojo/Webqq.pm line 5.
Compilation failed in require at GCM.pl line 1.
BEGIN failed--compilation aborted at GCM.pl line 1.
`

**Comment by sjdy521** [comment]
执行下cpanm IO::Socket::SSL 再安装Mojo::Webqq 试试

**Comment by tusooa** [comment]
看样子是没有装Mojolicious啊。

________________________________
