### ISSUE TITLE
【功能需求】webqq登录二维码通过微信接口发到微信？

### ISSUE THREAD

**Issue by bollwarm** [sjdy521/Mojo-Webqq#43]
webqq登录二维码通过微信接口发到微信（或者webqq的其他号）

当webqq挂掉时候，发送给微信账号消息，并把登录需要的二维码发送过。

然后实现手机扫描，登录webqq。

**Comment by sjdy521** [comment]
其实当前微信提供的发送消息api就已经支持发送图片了

**Comment by zjcnew** [comment]
webqq会实时检测QQ有没有在线吗？

在 2016年10月27日，19:05，Orange <notifications@github.com<mailto:notifications@github.com>> 写道：


webqq登录二维码通过微信接口发到微信（或者webqq的其他号）

当webqq挂掉时候，发送给微信账号消息，并把登录需要的二维码发送过。

然后实现手机扫描，登录webqq。

**Comment by sjdy521** [comment]
@zjcnew “webqq会实时检测QQ有没有在线吗？”这句没看懂

**Comment by zjcnew** [comment]
挂机过程中会自动下线，不知道为什么！

在 2016年10月28日，15:37，sjdy521 <notifications@github.com<mailto:notifications@github.com>> 写道：


@zjcnew<https://github.com/zjcnew> “webqq会实时检测QQ有没有在线吗？”这句没看懂

**Comment by sjdy521** [comment]
正常一天时候就会掉 要求重新扫码登录 你是挂多久掉的


发自网易邮箱大师
在2016年10月29日 12:59，zjcnew 写道:
挂机过程中会自动下线，不知道为什么！

在 2016年10月28日，15:37，sjdy521 <notifications@github.com<mailto:notifications@github.com>> 写道：


@zjcnew<https://github.com/zjcnew> “webqq会实时检测QQ有没有在线吗？”这句没看懂

**Comment by zjcnew** [comment]
两天吧，这个我作为运维生产环境的即时报警QQ用。

在 2016年10月29日，13:13，sjdy521 <notifications@github.com<mailto:notifications@github.com>> 写道：

正常一天时候就会掉 要求重新扫码登录 你是挂多久掉的


发自网易邮箱大师
在2016年10月29日 12:59，zjcnew 写道:
挂机过程中会自动下线，不知道为什么！

在 2016年10月28日，15:37，sjdy521 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> 写道：


@zjcnew<https://github.com/zjcnew> “webqq会实时检测QQ有没有在线吗？”这句没看懂

**Comment by sjdy521** [comment]
这个是正常的 不能长期保持在线


发自网易邮箱大师
在2016年10月29日 13:47，zjcnew 写道:
两天吧，这个我作为运维生产环境的即时报警QQ用。

在 2016年10月29日，13:13，sjdy521 <notifications@github.com<mailto:notifications@github.com>> 写道：

正常一天时候就会掉 要求重新扫码登录 你是挂多久掉的


发自网易邮箱大师
在2016年10月29日 12:59，zjcnew 写道:
挂机过程中会自动下线，不知道为什么！

在 2016年10月28日，15:37，sjdy521 <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> 写道：


@zjcnew<https://github.com/zjcnew> “webqq会实时检测QQ有没有在线吗？”这句没看懂

**Comment by sjdy521** [comment]
可以考虑用PostQRcode插件实现二维码图片发送到手机，随时使用手机扫码登录

**Comment by wsdjeg** [comment]
@zjcnew 我是通过neovim的job控制的，服务端一致挂着qq服务端,和一个辅助微信服务端，监听stdout，一旦掉线，脚本灰自动下载二维码，我是通过 job 的on_stdout，来通过neovim 执行另外一个脚本 将二维码发给我微信手机，然后我扫一下就ok了。

**Comment by zjcnew** [comment]
有详细配置文档吗，求一份，感谢！

在 2016年11月6日，20:17，Wang Shidong <notifications@github.com<mailto:notifications@github.com>> 写道：


@zjcnew<https://github.com/zjcnew> 我是通过neovim的job控制的，服务端一致挂着qq服务端,和一个辅助微信服务端，监听stdout，一旦掉线，脚本灰自动下载二维码，我是通过 job 的on_stdout，来通过neovim 执行另外一个脚本 将二维码发给我微信手机，然后我扫一下就ok了。

**Comment by shiyafeng** [comment]
smartqq腾讯已经不维护了 不定时就要重新登陆 你可以试试另一种稳定的方式 https://github.com/shiyafeng/foolqq
