### ISSUE TITLE
想请教下，如何做到扫描一次二维码，一直保持登录状态的？

### ISSUE THREAD

**Issue by linuxu2015** [sjdy521/Mojo-Webqq#46]
我用python实现了简单的功能，但是每隔1天左右就需要重新扫描登录，使用的是Mojo-webqq的docker，发现可以一直在线状态，非常感谢~

**Comment by sjdy521** [comment]
不行的 都是只能保持登录1～2天


发自网易邮箱大师
在2016年11月15日 10:17，linuxu2015 写道:

我用python实现了简单的功能，但是每隔1天左右就需要重新扫描登录，使用的是Mojo-webqq的docker，发现可以一直在线状态，非常感谢~

**Comment by linuxu2015** [comment]
好的，非常感谢~~还有个问题，那个postQRcode插件会在掉线后自动检测并发邮件吗？

**Comment by sjdy521** [comment]
对的


发自网易邮箱大师
在2016年11月15日 10:33，linuxu2015 写道:

好的，非常感谢~~还有个问题，那个postQRcode插件会在掉线后自动检测并发邮件吗？

**Comment by zjcnew** [comment]
@linuxu2015  
我用python实现了简单的功能，但是每隔1天左右就需要重新扫描登录，使用的是Mojo-webqq的docker，发现可以一直在线状态，非常感谢~

具体怎么实现，给个详细文档说明下，感谢。

**Comment by shiyafeng** [comment]
smartqq腾讯已经不维护了 不定时就要重新登陆 你可以试试另一种稳定的方式 https://github.com/shiyafeng/foolqq
