### ISSUE TITLE
请问1.8.8版本具体更新了什么内容

### ISSUE THREAD

**Issue by zjcnew** [sjdy521/Mojo-Webqq#47]
请问下1.8.8版本具体更新了什么内容，自动下线的问题能不能解决了？

**Comment by sjdy521** [comment]
版本更新内容全部会写在 Changes 文件中
自动下线是官方的限制，这个没办法解决的


发自网易邮箱大师
在2016年11月21日 12:02，zjcnew 写道:

请问下1.8.8版本具体更新了什么内容，自动下线的问题能不能解决了？

**Comment by zjcnew** [comment]
嗯，希望可以考虑一个解决自动登录的方案，因为我的webqq用在生产环境的云平台告警系统，这个下线问题实在太繁琐、太恶心了。感谢楼主的贡献


________________________________
发件人: sjdy521 <notifications@github.com>
发送时间: 2016年11月21日 12:06
收件人: sjdy521/Mojo-Webqq
抄送: zjcnew; Author
主题: Re: [sjdy521/Mojo-Webqq] 请问1.8.8版本具体更新了什么内容 (#47)

版本更新内容全部会写在 Changes 文件中
自动下线是官方的限制，这个没办法解决的


发自网易邮箱大师
在2016年11月21日 12:02，zjcnew 写道:

请问下1.8.8版本具体更新了什么内容，自动下线的问题能不能解决了？

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by sjdy521** [comment]
当前基于webqq和企业办公对接很难满足要求，最近还发现官方的w.qq.com在浏览器里访问都有问题… 不知道官方什么时候修复

1、考虑多个qq账号具备
2、自己及时定期扫码重新登录
3、建议使用Mojo-Weixin微信更稳定

**Comment by zjcnew** [comment]
还有个问题，我是用的Mojo-ActivePerl集成webqq环境，请问webqq怎么升级到1.8.8版本，我看Mojo-ActivePerl代码包没有更新。


________________________________
发件人: sjdy521 <notifications@github.com>
发送时间: 2016年11月21日 12:14
收件人: sjdy521/Mojo-Webqq
抄送: zjcnew; Author
主题: Re: [sjdy521/Mojo-Webqq] 请问1.8.8版本具体更新了什么内容 (#47)


当前基于webqq和企业办公对接很难满足要求，最近还发现官方的w.qq.com在浏览器里访问都有问题… 不知道官方什么时候修复

1、考虑多个qq账号具备
2、自己及时定期扫码重新登录
3、建议使用Mojo-Weixin微信更稳定

―

**Comment by sjdy521** [comment]
使用Mojo-ActivePerl安装目录下的cpanm进行更新，比如你的Mojo-ActivePerl安装在/usr/local/Mojo-ActivePerl，则使用如下命令来更新版本：

`/usr/local/Mojo-ActivePerl/bin/cpanm Mojo::Webqq`
