### ISSUE TITLE
关于 openqq 上报图片消息的疑问

### ISSUE THREAD

**Issue by bdbai** [sjdy521/Mojo-Webqq#48]
`Openqq.pm` 里面注释说 `#发送图片，暂未实现 `，我想问一下将来会实现吗？实现的难点在哪里呢？

**Comment by sjdy521** [comment]
腾讯官方不支持，估计实现的可能性很小，目前只有Mojo-Weixin才支持发图

**Comment by bdbai** [comment]
明白了，感谢 repo 主。
