### ISSUE TITLE
似乎有时候群消息发不出去

### ISSUE THREAD

**Issue by richardchien** [sjdy521/Mojo-Webqq#49]
我部署到服务器之后群消息似乎发不出去，log 里显示发了，但是没有收到，在本机开的时候，是可以的，是因为腾讯的异地登录限制吗……

**Comment by sjdy521** [comment]
对的，一般都是因为腾讯的问题导致的，不太稳定

**Comment by laysdra7265** [comment]
我用過另一個webqq的機器人API，
群發消息調用的URL有時候會返回錯誤然後發送失敗，我發現後修改了源碼讓他在URL返回錯誤的時候會定時重發，會不會是同一個問題?

**Comment by laysdra7265** [comment]
我用過另一個webqq的機器人API，
群發消息調用的URL有時候會返回錯誤然後發送失敗，我發現後修改了源碼讓他在URL返回錯誤的時候會定時重發，會不會是同一個問題?如果是這樣應該是可以偵測發送失敗的吧?

**Comment by sjdy521** [comment]
如果明确知道是发送失败了，会自动内部重试多次的，但实际上会存在官方告知发送成功，但是实际上根本没有发送成功的情况，甚至存在官方告知发送失败但实际上却发送成功的情况，这个就很没办法了，不过发送消息不成功的情况目前应该并不多，你可以多测试下

**Comment by sjdy521** [comment]
也可能确实是异地登陆的限制，可以多登录一下 或者手机下载qq安全中心的app来修复下异地登陆的警告

**Comment by bollwarm** [comment]
如果字数太多也会发送不成功的
