### ISSUE TITLE
接受好友消息时，$msg-{sender}->{nick} 获取不到昵称的问题

### ISSUE THREAD

**Issue by wxg4net** [sjdy521/Mojo-Webqq#5]
最新版本
只有少部分不能接受到，大部分正常。但是好友列表里面的昵称显示正常。

**Comment by sjdy521** [comment]
经过测试暂无法重现问题，继续观察
另外，基于Mojolicious的框架，对象的方法都不再使用老版本hash的访问形式
$msg-{sender}->{nick} 建议改为 $msg-sender->nick
