### ISSUE TITLE
【通知】Mojo-Webqq正在进行2.0版本重构，将和现有的1.x.x版本不兼容

### ISSUE THREAD

**Issue by sjdy521** [sjdy521/Mojo-Webqq#51]
新版本将进行大量的重构，以便和Mojo-Weixin项目尽量统一，清理杂乱代码，同时增加更多新的特性，不清楚有多少人正在使用这个项目，没办法一一通知到，可能的变更包括：

*  对象属性的重新命名，比如
    1）消息对象 
        原先的`msg_class/msg_id/msg_from`等变更为`class/id/from`，去掉msg_开头
        好友消息类型从 `message` -> `friend_message`
    2）对象属性 
          `nick`->`name` 
          `qq`->`uid`  
          `gname` -> `name`
          `gnumber` -> `uid`
         `gtype` -> `role`
         `did` -> `id`
* 对象属性变化也会体现在Openqq的接口接口地址和上报的数据和请求参数中
    1）`/openqq/send_message` -> `/openqq/send_friend_message`
    2） 请求参数中的使用`id/uid/group_id/discuss_id`等，不再支持原有的`gid/gnumber/did`

* 内部编码进行了统一，尽量去unicode，http_get/http_post 提交和获取的json数据，可以直接使用utf8编码字节流，不再需要encode/decode转换

* 内建$client->encode/decode/encode_utf8/from_json/to_json等方法，不再需要自己加载外部的Encode模块等

* 日志新增msg级别，`debug|info|msg|warn|error|fatal` 专用与打印接收和发送的消息，方便和系统其他级别日志做区分

* 去掉了单进程多帐号的支持，每个进程只能支持一个帐号，后续会类似`Mojo-Weixin`提供`Mojo::Webqq::Controller`来统一管理多账号

* `Mojo::Webqq->new(qq=>xxxx)` 变更为 `Mojo::Webqq->new(account=>xxxx) ` account可以自定义，不再强制要求使用qq号

* 新增终端彩色日志打印，需要先安装`Term::ANSIColor`模块

**Comment by laysdra7265** [comment]
期望也能順便加強OPENQQ的功能

**Comment by zjcnew** [comment]
其实目前open QQ的功能已经够强了，也足够用了。我只希望能够最好有解决自动扫码登陆，解决长期自动在线以及收发消息成功的问题。每天我都扫码登陆的频繁操作已经让我反感至极了！

在 2016年12月23日，22:54，laysdra7265 <notifications@github.com<mailto:notifications@github.com>> 写道：


期望也能順便加強OPENQQ的功能

**Comment by sjdy521** [comment]
每天都扫码的问题暂时解决不了额 腾讯的限制 没办法 其他方面咱能改善的都会尽量去做

**Comment by zjcnew** [comment]
嗯，我只是希望有更好的解决办法，同时感谢作者无私的贡献。

在 2016年12月24日，00:44，sjdy521 <notifications@github.com<mailto:notifications@github.com>> 写道：


每天都扫码的问题暂时解决不了额 腾讯的限制 没办法 其他方面咱能改善的都会尽量去做
