### ISSUE TITLE
新2.0 bata API测试

### ISSUE THREAD

**Issue by bollwarm** [sjdy521/Mojo-Webqq#53]
通过手动调用接口（除了管理接口）都已经通过没问题，除了在发送消息时候如果消息中间有空格（空格和tab）都会失败。：

1、测试成功用例（包括预期失败的调用）

 curl http://127.0.0.1:5000/openqq/get_friend_info
 curl  http://127.0.0.1:5000/openqq/get_group_basic_info >bgroup.list
 curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=30705478&content=%e4%bd%a0%e5%a5%bd"
 curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=30705478&content='你好'"
 curl "http://127.0.0.1:5000/openqq/send_friend_e&content='你好'"
 curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=30705478&content='你好'"
 curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=&content='你好'"
 curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=308165330&content='你好的'"（不是好友，不成功）
 curl "http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content='群消息测试\n中文\rtest'"
 curl "http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content='群消息测试\n中文\ rtest'"
 curl 'http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content="群消息测试\n中文\\rtest"'
 curl 'http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content="群消息测试\n中文\\@桔子rtest"'
 curl 'http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content="群消息测试\n中文@桔子rtest"'
 curl 'http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content="群消息测试\n中文\\@桔子/wxrtest"'
 curl 'http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content=/pz'
 curl http://127.0.0.1:5000/openqq/search_friend?uid=30705478
 curl 'http://127.0.0.1:5000/openqq/search_group?uid=498880156'
 curl 'http://127.0.0.1:5000/openqq/shutup_group_member?uid=498880156&member_uid=874490076&time=20'(不是管理员，不成功)

2、连个失败的测试用例：

curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=qq号&content='你 好的'"
curl "http://127.0.0.1:5000/openqq/send_group_message?uid=498880156&content='群消息测试\n中文\\ rtest'"

另外 curl http://127.0.0.1:5000/openqq/get_discuss_info 获取为空，是不是不在支持这功能

**Comment by sjdy521** [comment]
http://127.0.0.1:5000/openqq/get_discuss_info 获取为空 
是否有可能是设置了 is_init_discuss=>0 我测试是可以正常获取的

curl "http://127.0.0.1:5000/openqq/send_friend_message?uid=qq号&content='你 好的'"
这种请求不合法，需要做urlencode
