### ISSUE TITLE
irc webqq和weixin同时在线有冲突

### ISSUE THREAD

**Issue by 217LeeSin** [sjdy521/Mojo-Webqq#56]
irc使用的是同一个端口，所以webqq和微信同时在线有冲突，请问这个应该怎么办，可以修改端口或者是什么吗

**Comment by bollwarm** [comment]
可以修改端口

**Comment by sjdy521** [comment]
@217LeeSin
需要微信和webqq的IRCShell插件设置不同的IRC Server端口，比如一个用6666，一个用6667（IRC协议默认端口）
任意IRC的客户端都支持同时连接多个IRC Server的，具体可以查询下客户端的用法，一般是
`/server` `/connect`等irc指令

```
$client->load("IRCShell",data=>{
        listen =>[{host=>"0.0.0.0",port=>6667},],
});
```
```
$client->load("IRCShell",data=>{
        listen =>[{host=>"0.0.0.0",port=>6666},],
});`
```
