### ISSUE TITLE
Exception when receviced a new_group_member message.

### ISSUE THREAD

**Issue by kliner** [sjdy521/Mojo-Webqq#57]
[17/01/06 14:44:41] [info] 更新群组[ 这是一个群 ]信息
[17/01/06 14:44:42] [info] 更新群组[ 这是一个群 ]成员扩展信息
[17/01/06 14:44:42] [error] Can't call method "to_json_hash" on an undefined value at /Users/kliner/perl5/lib/perl5/Mojo/Webqq/Plugin/Openqq.pm line 69.

**Comment by sjdy521** [comment]
这个问题在1.2.1版本中已经修复 可以执行 `cpanm Mojo::Webqq` 自动升级下

**Comment by kliner** [comment]
升级没有问题了，但是还是收不到 new_group_member 的 event，帮忙确认一下

**Comment by sjdy521** [comment]
可以看下这里的说明
https://metacpan.org/pod/distribution/Mojo-Webqq/lib/Mojo/Webqq.pm#客户端事件

常见的事件发生时，比如接收到消息，有人加入群中等等，客户端会设置对应的事件名称，并在事件完成时进行触发

你可以使用$client->on(event=>sub{xxx})的方式对你感兴趣的事件注册回调函数，回调函数的第一个参数永远是客户端对象本身

注意：

new_friend/new_group/new_discuss/new_group_member/new_discuss_member
lose_friend/lose_group/lose_discuss/lose_group_member/lose_discuss_member
这类事件采用的是较为特殊的处理方式，比如新增群成员时，如果你的帐号是管理员权限，你会收到相关的通知

但如果是非管理员权限,则完全不会收到任何通知提醒，以新增群成员为例，为了统一实现功能，采用两种机制:

1）客户端定期更新好友、群组、讨论组数据，和原始数据对比来发现新增或者丢失的成员，当前定期更新频率为10分钟

2）当群成员在群里发言时，客户端会马上在数据库中搜索相关群成员，如果搜索不到则判断为新增群成员，马上更新数据库，并触发事件

因此，你可能会发现当群成员加入后，过了10分钟才会触发相关的事件，或者新增群成员一旦发言也会发送触发事件

**Comment by kliner** [comment]
Got it. Thanks a lot.
