### ISSUE TITLE
请问一下PostQRcodeToTelegram插件是怎么用的

### ISSUE THREAD

**Issue by yangchuansheng** [sjdy521/Mojo-Webqq#58]

**Comment by sjdy521** [comment]
@HubertZhang 你的问题来啦

**Comment by HubertZhang** [comment]
@yangchuansheng 这个是用来把二维码通过Telegram Bot发送给指定用户的。

大概是先申请一个Telegram Bot然后在client中加载插件并填入对应的参数

参见
https://github.com/sjdy521/Mojo-Webqq/blob/master/lib/Mojo/Webqq.pod#Mojo::Webqq::Plugin::PostQRcodeToTelegram

**Comment by sjdy521** [comment]
已经把该插件加入到[插件列表](Plugin.md)中
