### ISSUE TITLE
文档中 终止程序运行 的API是笔误吗

### ISSUE THREAD

**Issue by knowncold** [sjdy521/Mojo-Webqq#68]
[http://127.0.0.1:5000/openwx/stop_client](http://127.0.0.1:5000/openwx/stop_client)  
应该是  
[http://127.0.0.1:5000/openqq/stop_client](http://127.0.0.1:5000/openqq/stop_client)  ?

**Comment by bollwarm** [comment]
那应该是

**Comment by bollwarm** [comment]
已经修正
