### ISSUE TITLE
使用OpenQQ模块发送群消息的问题

### ISSUE THREAD

**Issue by go3k** [sjdy521/Mojo-Webqq#7]
今天从pfqq切换到这个工程，发现使用如下格式发送群消息会报错：group not found

>  /openqq/send_group_message?gnumber=xxx&content=xxx

只有，使用gid参数才能发送成功：

> /openqq/send_group_message?gid=xxx&content=xxx

但是问题是gid字段并不直观，是新版OpenQQ模块有bug吗？还是`search_group`这个接口有bug？

**Comment by sjdy521** [comment]
gnumber这个参数表示真实的群号，gid只是本次登录时群对应的标识
旧版本使用Webqq::Qun这个模块来登录+批量获取到群号和群成员的QQ号，然后再将这些信息融合到pfqq自身的数据中，才能够实现通过gnumber找到gid实现发送消息

但上述实现方式非常"绕弯"，而且不是100%可靠的，新版本Mojo::Webqq暂时没有支持gnumber这个参数，通过gid字段确实不直观，很影响使用，这方面一直是一个"刺"，用起来很难受

建议暂时先通过openqq的 /openqq/get_group_info 获取到群的信息，提取出gid，再通过gid发送消息
我会考虑下把旧版本这个gnumber的支持也迁移过来

**Comment by go3k** [comment]
@sjdy521 期待尽快支持。。

**Comment by sjdy521** [comment]
@go3k 本来是打算利用Mojo重写Webqq::Qun之后再集成的，看样子是等不及了。

**Comment by sjdy521** [comment]
整个特性确实是非常期待的，我一直在积蓄这方面的探索，登录了smartqq就意味着你直接登录了群管理功能，邮箱功能，甚至QQ空间等其他腾讯基于web的产品，理论上这些功能都可以集成到Mojo::Webqq客户端上，只是目标有些庞大。。要慢慢实现


发自 网易邮箱大师
在2015年10月08日 21:41，Vincent Chou 写道:

@sjdy521 期待尽快支持。。

**Comment by go3k** [comment]
:thumbsup:

**Comment by sjdy521** [comment]
支持群号码 好友qq号码发送消息功能即将发布，敬请期待，同时还添加了设置群名片，踢人，邀请好友入群，设置管理员等更多群管理功能

**Comment by sjdy521** [comment]
v1.5.5版本已经支持使用qq号和群号发送消息，请确认
https://github.com/sjdy521/Mojo-Webqq/commit/502bab3289601991bff1a7469f4b0ba75147b51b

**Comment by go3k** [comment]
太赞！:thumbsup:

另外，能够做到删除本地过期的二维码文件吗？有时会堆积很多。

**Comment by sjdy521** [comment]
@go3k 本地二维码文件堆积过多的问题，有几种思路：
1、自己在运行webqq之前先清理文件，比如
unlink glob '/tmp/webqq_qrcode_*.png';
my $client=Mojo::Webqq->new(xxx);
这个有必要的话 我会可以把unlink集成到Mojo::Webqq的代码里

2、通过new的qrcode_path参数指定保存二维码的路径，比如
my $client->new(qrcode_path=>"./qrcode.png");
使用固定的文件路径，下载到的新二维码会覆盖旧的文件，这样就不会产生很多这随机生成一个二维码文件名称到临时目录下

**Comment by go3k** [comment]
多谢

**Comment by go3k** [comment]
经验证，新版可以使用gnumber参数正常发送群消息。

**Comment by sjdy521** [comment]
:D

**Comment by sjdy521** [comment]
删除本地过期的二维码文件，功能已经集成
https://github.com/sjdy521/Mojo-Webqq/commit/d33f10438615dc8fdde6b466d0f908c7288e0870

**Comment by gitlsl** [comment]
so nice

**Comment by go3k** [comment]
用了几天发现openqq群消息经常发送失败，看日志发现更新群列表信息失败。这会导致使用gnumber参数找不到指定的群吗？
下面是我重登陆操作后的日志：

[15/10/14 09:57:30] [info] 检测到最近登录活动，尝试直接恢复登录...
[15/10/14 09:57:30] [info] 获取数据验证参数...
[15/10/14 09:57:31] [info] 尝试进行登录(2)...
[15/10/14 09:57:31] [info] 帐号(xxxx)登录成功
[15/10/14 09:57:31] [info] 更新个人信息...
[15/10/14 09:57:31] [warn] 更新个人信息失败
[15/10/14 09:57:31] [info] 更新好友信息...
[15/10/14 09:57:31] [warn] 更新好友信息失败
[15/10/14 09:57:31] [info] 更新好友扩展信息...
[15/10/14 09:57:31] [warn] 更新好友扩展信息失败
[15/10/14 09:57:31] [info] 更新群列表信息...
[15/10/14 09:57:31] [warn] 更新群列表信息失败
[15/10/14 09:57:31] [info] 更新群扩展信息...
[15/10/14 09:57:31] [warn] 更新群扩展信息失败
[15/10/14 09:57:31] [warn] 更新讨论组列表信息失败
[15/10/14 09:57:31] [info] 更新最近联系人信息...
[15/10/14 09:57:34] [info] http server available at 127.0.0.1:5000
[15/10/14 09:57:34] [info] 开始接收消息...

**Comment by hzz1989** [comment]
@go3k 在手机QQ上注销网页登录，再在主机重新登录试试。我之前也遇到过，重新登录后就好了。

**Comment by sjdy521** [comment]
@go3k 你客户端new的时候 有指定qq号码吗

**Comment by sjdy521** [comment]
首先，当前Mojo-Webqq在运行一段时间之后 一定会出现无法更新好友、群组信息的情况，可能是某些相关cookie过期导致的，更新失败客户端就会使用旧的数据，只是这期间如果有新增群成员或新增好友就无法感知到 也无法发送信息了，旧的好友和群成员仍然可以正常发送

早期的版本遇到这种情况直接重新登录（客户端退出 重新运行 或者调用->relogin() ），就可以保证更新成功，新的版本加入了登录cookie检测和快速恢复登录的功能，也就是日志中打印的：

[15/10/14 09:57:30] [info] 检测到最近登录活动，尝试直接恢复登录...
[15/10/14 09:57:30] [info] 获取数据验证参数...
[15/10/14 09:57:31] [info] 尝试进行登录(2)...
[15/10/14 09:57:31] [info] 帐号(xxxx)登录成功

这其实相当于没有完全重新登录，仍然使用上一次登录的旧cookie，所以就可能出现登录后仍然更新信息失败的情况，最新的github源码中在model_update_fail这个事件说明中有大概提到这方面的问题，

model_update_fail这个事件是当更新好友信息、群信息等联系三次失败就触发（一次失败可能是因为网络原因等），可以在这个事件触发时重新登录

 $client->on(model_update_fail=>sub{
        $client = shift;
        $client->relogin();
    });

或者 你直接删除/tmp/mojo_webqq_cookie_(你的qq号).dat 这个cookie文件就可以解决这个问题了

但重新登录就会需要再次扫描二维码，这也是无法避免的
不管怎么说，我客户端已经退出的情况下，重新启动客户端 不应该出现更新失败的情况，这种情况下连好友信息、群信息这些基本的信息都拿不到，那所有的相关功能都无法正常工作，这是不应该的，我会尽快修复下

**Comment by sjdy521** [comment]
@go3k @hzz1989 
bug已经修复，还请多帮忙测试确认
https://github.com/sjdy521/Mojo-Webqq/commit/18af52022ff574f5de622f8ca26f6959c0967715

**Comment by sjdy521** [comment]
sorry 已经确认启动后过10分钟 程序会更新一次数据库，更新会导致gnumber等信息丢失，无法通过Openqq发送消息了，正在想办法修复

**Comment by sjdy521** [comment]
bug已经彻底修复
https://github.com/sjdy521/Mojo-Webqq/commit/fbcd3b6049ed745c41a9096d214ba44a759f244f

**Comment by go3k** [comment]
收到，我再跑跑看

**Comment by hzz1989** [comment]
@go3k @sjdy521 为啥我的还是group not found呢，已经更新到最新版了。

[nagios@huangzhonzhang qq-sms]$ curl http://127.0.0.1:5000/openqq/send_group_message?gnumber=498630857&content=123
[1] 27417
[nagios@huangzhonzhang qq-sms]$ {"status":"group not found","msg_id":null,"code":101}
[1]+  Done                    curl http://127.0.0.1:5000/openqq/send_group_message?gnumber=498630857
[nagios@huangzhonzhang qq-sms]$

**Comment by sjdy521** [comment]
url加个引号试试？


发自 网易邮箱大师
在2015年10月17日 16:23，Finder 写道:

@go3k@sjdy521 为啥我的还是group not found呢，已经更新到最新版了。

[nagios@huangzhonzhang qq-sms]$ curl http://127.0.0.1:5000/openqq/send_group_message?gnumber=498630857&content=123
[1] 27417
[nagios@huangzhonzhang qq-sms]$ {"status":"group not found","msg_id":null,"code":101}
[1]+ Done curl http://127.0.0.1:5000/openqq/send_group_message?gnumber=498630857
[nagios@huangzhonzhang qq-sms]$

**Comment by hzz1989** [comment]
@sjdy521 还是不行，用gid就可以。

[nagios@huangzhonzhang qq-sms]$ curl "http://116.255.150.128:5000/openqq/send_group_message?gnumber=498630857&content=123"
{"status":"group not found","msg_id":null,"code":101}[nagios@huangzhonzhang qq-sms]$ 
[nagios@huangzhonzhang qq-sms]$ 
[nagios@huangzhonzhang qq-sms]$ 
[nagios@huangzhonzhang qq-sms]$ curl "http://116.255.150.128:5000/openqq/send_group_message?gid=3595270022&content=123"   
{"status":"发送成功","msg_id":14340001,"code":0}[nagios@huangzhonzhang qq-sms]$ 
[nagios@huangzhonzhang qq-sms]$

**Comment by sjdy521** [comment]
$_->dump for $client->groups;
登录后 上面代码运行结果单独发我邮箱看看

**Comment by sjdy521** [comment]
@hzz1989 
感谢提供测试环境，已经确认是由于32位系统大整数溢出导致的计算结果错误，在1.5.8版本中已经修复
你机器上的perl代码也已经手动修改了可以正常使用

**Comment by hzz1989** [comment]
@sjdy521 非常感谢，终于可以愉快地玩耍了。：D

**Comment by sjdy521** [comment]
@hzz1989 需要提醒一点 如果是打算拿来做监控报警，基于网页的webqq每2~3天会被强制下线重新登录一次，以前帐号密码的方式可以完成自动登录，现在要二维码扫描就必须自己亲自手动扫描了 也就是说程序没办法持续长时间保持在线了，腾讯的限制 没办法

**Comment by hzz1989** [comment]
@sjdy521 没事，这只是试验性地弄一下而已，不是完全依赖这个功能。而且开启了二维码邮件发送功能，当收到邮件时就知道被下线了，重新扫一次就是。:-)
对于被强制下线，能不能定时由程序主动下线，然后利用cookie再次登录呢？利用cookie登录的话，不知在腾讯看来，是不是重新登录。

**Comment by sjdy521** [comment]
cookie登录早就支持了，如果是强制下线cookie已经失效了没办法再利用cookie登录

**Comment by hzz1989** [comment]
@sjdy521 我的意思是，不要等强制下线。当登录满一天后，由程序主动下线，然后利用cookie上线，让腾讯误以为是用户重新登录了，然后重新开始倒计时。就跟很多软件无限延长试用期的方式一样。不知道能不能实现。

**Comment by sjdy521** [comment]
感觉腾讯应该不会因为重新登录而重现计算登录时长 不过可以尝试下 说不定呢:D

**Comment by sjdy521** [comment]
@hzz1989 
$client->timer(86400,sub{$client->login()});
就可以实现每隔86400s（一天）重新登录一次了，并且登录是可以复用之前的cookie的

**Comment by hzz1989** [comment]
@sjdy521 好，那我就来试试，看用这种方法能不能永久在线。:-D

**Comment by gitlsl** [comment]
why you so diao?

**Comment by hzz1989** [comment]
@sjdy521 Sorry，还是没能坚持超过3天…… :-(

**Comment by sjdy521** [comment]
@hzz1989 哈哈 没事
加Mojo-Webqq的群吧 有事情讨论比较方便 498880156
