### ISSUE TITLE
提个不成熟的意见，灰灰能否把API接口的极个别字段名称修改一下？

### ISSUE THREAD

**Issue by indiboy** [sjdy521/Mojo-Webqq#70]
比如说 group 这个就是个保留词，使用的时候不是很方便
还有就是 id ,大家建数据表时候都习惯用id, 然而 json 里面也有id这个字段
能否修改成 group_name  user_id message_id  group_id?

不知道我这样想对不对。写起来的话也不容易写错。

**Comment by sjdy521** [comment]
感谢交流，非常愿意一起讨论这样的程序设计问题
这个其实在我看来没有想的这么简单，说来话长
1、"group这个保留词，使用不方便" -->这方面没懂，你所使用的语言中`group`是一个程序保留字？
     至少在我的项目里`group`是比较清晰的定义的，很难再开发的时候顾及太多其他系统或语言的情况

2、关于json里的id字段，首先json数据其实就是程序中对象属性的直接映射，比如一个好友对象
```
Object(Friend)
  +----> id
  +---->name
```
对于的json数据就是{"id":xxx, "name":xxx} 
这种方式，json在输出的时候不需要去做再次的属性名称转换
可以提供一个统一的转换函数，代码维护起来会更简单，任何对象都可以使用这个转换函数来把自身的属性转换成json字符串，

3、关于对象的属性是否要做更明确区别的问题（`user_id` `message_id` `group_id`）
早期1.x.x版本的时候采用的是类似的思路，但是经过一段时间的代码维护，最终在2.x.x版本中放弃了这种设计
```
1.x.x中的对象属性设计
好友对象 ($object->id) 
群对象($object->gid)
消息对象($object->msg_id)
```
理由其实有很多：
1）从面向对象的程序设计角度来说，对象中共性的东西统一出来，有利用充分利用抽象+继承的特性
比如我可以设计一个基类，只有id信息，其他类继承该基类的方法，扩展更多自己的属性，
基类可以提供一些基本的方法，id最主要的作用就是唯一识别一个对象，所以经常会拿来判断或搜索指定对象
```
Object(Base)
  + --->id
  +---->search_object()
  +---Object(Friend)
  +         +--->Sex
  +---Object(Group)
             +--->member
```
`$object = search_object(id=>xxx);`
如果id的名称每个对象都做单独区分，那在代码中，你就需要自己去区分各种对象类型来写不同的函数
search_friend(friend_id)
search_friend(group_id)
search_msg(msg_id)
极大的阻碍了代码复用，对代码维护造成了很大的困扰

2）再举个例子，很多时候，我们经常涉及到对方（可能是群或者好友）发来一个消息，你需要回复它
回复消息的时候需要用到id，如果对象属性是足够统一的，回复消息的代码会变得非常简单

`reply($object->id=>xxxx,content="回复消息")`

这个过程中，你编写的reply函数根本不需要关心对象是什么类型，只需要调用$object->id获取到id，就可以了
否则你可能就要这样写：
```
if($object 是 好友){
    reply($object->friend_id,content=>"你好");
}
elsif($object 是 群){
    reply($object->group_id,content=>"你好");
}
```
这种情况充斥在代码里的方方面面，你会发现明明一行代码或一个函数可以搞定的事情，你不得不要分开写成多行代码，多个函数，我觉得这是一种很糟糕的设计，破坏代码本身的优雅，所以我才逐步放弃了这种想法


从最终的效果来看，我觉得在每个固定的接口场景下，id都具备明确的意义，并不会存在混淆
你在数据库见表的时候，如果一张表里囊括所有的信息，比如一张表：
`id|group_id|user_id|message_id|friend_id`
我认为是一种比较糟糕的设计，推荐你把消息、群、好友等不同类型分别建表


已上是我的一点想法

**Comment by indiboy** [comment]
多谢老大回复这么多，我用的是php写的上报接口， group 这个词写mysql的时候常用group by xxx之类的。

还有就是ID，原因是我初建表的时候就是用的id这个字段，然后才是上报接口的字段(JSON里面的)，所以JSON里面的和这个id有点冲突，因此信息入库的时候需要把这个id换为其他的，比如说user_id message_id group_id，就多了一个步骤，如果JSON里没有ID这个字段的话，我就可以直接把json入库了。然后数据表的id是个自增ID。你写的我也基本看明白了，但是id这个字段，对于一个系统来说都是很好的，但是我是把这个JSON提交到我已经做好的系统，而数据表里面已经有ID这个字段了，这两个ID就冲突了。

你的这个id在很多json里面都有，表述的意思也不一样，有些甚至是变化的（讨论组），我觉得并不能完全表达id的意思。我印象中的id就是个排序，序号，自增。

我建议这个id可以改名叫hui_id，哈哈哈，感谢回复，支持老大。

**Comment by sjdy521** [comment]
你的意思我也懂了，这个问题在我设计的时候还真的是没有考虑到，我在深入思考下以后如何应对

目前看起来就是id这个名字在不同的系统之间传递的时候会存在冲突，尤其是数据库建表里面
大家都喜欢用id这个名字，但不同系统之间交互必然需要做转换处理，现在就看这个转换处理是放在哪边来做

目前看起来我这边做或者你这边做，效果是一样的，但我这边改动起来会麻烦很多，估计我所有的源码文件都要被改动……而且现在依赖这个项目的人比较多，这种改动会导致不兼容，影响范围会比较大
我想想有没有其他什么好的方式

所以，当前来看，暂时还是得你这边辛苦下:-)
可以写个php的函数，获取到我的数据之后，把我所有的id都直接替换为hui_id，然后再交由你程序的其他部分去处理

**Comment by indiboy** [comment]
老大辛苦！~~
