### ISSUE TITLE
smartReply doesn't work

### ISSUE THREAD

**Issue by liusijiang** [sjdy521/Mojo-Webqq#73]
不知道有没有人注意到使用图灵 api 的智能回复不能工作了。
我不会 perl，所以没有去看。哪位有空看看是否是这样。

**Comment by sjdy521** [comment]
等找时间我测试下哈

**Comment by liusijiang** [comment]
这个插件中间过程要是能打印 log 就更好了。

**Comment by sjdy521** [comment]
经过测试，当前存在无法回复好友消息的bug，已经修复
需要使用github最新代码来测试，参考FAQ.md
https://github.com/sjdy521/Mojo-Webqq/blob/master/FAQ.md#3-如何使用github上最新的代码进行测试

**Comment by liusijiang** [comment]
怪不得，谢谢你啦。
