### ISSUE TITLE
大神，有没有准备用Python 写一套？

### ISSUE THREAD

**Issue by ocswor** [sjdy521/Mojo-Webqq#74]
可惜没有python版本，大神，有没有准备用Python 写一套？
第二个问题是，使用接口 如何获取群组消息？

**Comment by sjdy521** [comment]
如果是通过http api的方式使用的话，用什么语言都无所谓，pthon写一套的意义就不大了
另外，现在精力有限，实在是没有精力去搞新的一套

接口获取群组消息看下这两个API接口文档介绍
1）https://github.com/sjdy521/Mojo-Webqq/blob/master/API.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6%E6%B6%88%E6%81%AF%E4%B8%8A%E6%8A%A5%E5%9C%B0%E5%9D%80
2）https://github.com/sjdy521/Mojo-Webqq/blob/master/API.md#%E6%9F%A5%E8%AF%A2%E4%BA%8B%E4%BB%B6%E6%B6%88%E6%81%AF

**Comment by gitlsl** [comment]
建议所有的插件都用 http 实现 ！

**Comment by sjdy521** [comment]
其实基于http接口做开发的话 根本不需要使用当前提供的插件, 自己用熟悉的语言写一个就行啦，完全可以实现现有所有插件的功能
