### ISSUE TITLE
请求授权迁移此项目中的基于qun.qq.com的部分到自己的项目

### ISSUE THREAD

**Issue by TJYSunset** [sjdy521/Mojo-Webqq#77]
我知道这种东西大概不应该发在这里，但是gitter上没人理我→_→
我在做一个[SmartQQ的封装](https://github.com/tjysunset/dumbqq)，想要迁移此项目中的群管理部分，但是不想把license改成GPL，问一下能否授权我这么做？

**Comment by sjdy521** [comment]
放心去做吧，骚年～

**Comment by TJYSunset** [comment]
好的，谢谢:D
