### ISSUE TITLE
是否支持隐身登陆？

### ISSUE THREAD

**Issue by grittiness** [sjdy521/Mojo-Webqq#79]
登陆QQ的时候能实现隐身吗？

**Comment by sjdy521** [comment]
Mojo::Webqq->new(mode=>"hidden") 
以前网页版是支持设置登陆状态的，但现在不太知道还行不行了，可以试验下，原则上主要官网网页版支持我们就都可以支持

**Comment by grittiness** [comment]
好的，我试试   感谢回复~
