### ISSUE TITLE
关于返回好友在线状态的api问题

### ISSUE THREAD

**Issue by JeffreyFish** [sjdy521/Mojo-Webqq#81]
貌似现在基于WebQQ的api返回的还有在线状态都不是很准。
我试过的两个返回好友状态的api都是如此：
http://d1.web2.qq.com/channel/get_online_buddies2?vfwebqq=#{vfwebqq}&clientid=53999199&psessionid=#{psessionid}&t=0.1

http://s.web2.qq.com/api/get_friend_info2?tuin=#{uin}&vfwebqq=#{vfwebqq}&clientid=53999199&psessionid=#{psessionid}&t=0.1

比如：用iphone和电脑同时登录的qq，用这个api还是无法返回，一定要只有电脑客户端在线才会返回online的状态。

请问有没有啥api可以比较准确返回某个好友的在线状态吗？

**Comment by bollwarm** [comment]
pc端，手机端也不能准确返回吧

**Comment by JeffreyFish** [comment]
手机端的相对好一些，起码不会明明iphone在线，却没返回online的状态，所以感觉手机端的在线状态的api会准确很多。

**Comment by JeffreyFish** [comment]
@bollwarm 手机端的相对好一些，起码不会明明iPhone在线，却没返回online的状态，所以感觉手机端的在线状态的api会准确很多。

**Comment by sjdy521** [comment]
想要获取这个信息的目的数据什么

**Comment by JeffreyFish** [comment]
@sjdy521 就是要想比较准确判断该好友的在线状态呀

**Comment by sjdy521** [comment]
目前获取好友状态就两种方式：
1、http://d1.web2.qq.com/channel/get_online_buddies2接口
2、好友上线时，心跳poll请求会产生相应的系统消息通知
