### ISSUE TITLE
mac 系统安装找不到 cpanm命令

### ISSUE THREAD

**Issue by jackPanyj** [sjdy521/Mojo-Webqq#91]
shell 已经重启了。
![image](https://cloud.githubusercontent.com/assets/12585605/24068326/03e45ff2-0bc7-11e7-8498-fe7181e3bff4.png)

**Comment by sjdy521** [comment]
这个问题主要原因是你在非root环境下安装，没有写入系统lib目录的权限，因此写入到/home/panshao/perl5 目录下，你的cpanm实际上就是装在这里的

你的截图里也有提示你要消除警告需要执行给定的命令来安装local::lib

安装完这个local::lib之后 再把如下代码写入你的～/.bashrc 确保以后每次启动都在shell中加载local::lib 即可

eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
详细参考：
https://metacpan.org/pod/local::lib

**Comment by jackPanyj** [comment]
直接软连接到系统lib目录可以吗

**Comment by sjdy521** [comment]
不推荐用sudo，如果用sudo的话 尽量确保从cpanm安装到后续程序的运行全部加sudo 这样才能保证运行用户和权限的统一，否则可能会因为sudo是root权限安装的 如果实际运行又是非root可能会报permiso deny之类的错误
