### ISSUE TITLE
群名片的完整性

### ISSUE THREAD

**Issue by waylonwang** [sjdy521/Mojo-Webqq#93]
貌似Web QQ本身的群名片就是被截断了的，导致Web QQ的API中的用户群昵称都是不完整的，Mojo-Webqq看看有没有其他办法可以解决这个问题？我发现酷Q的群昵称是完整的，好像也是用了qun.qq.com和cookie来实现的

**Comment by waylonwang** [comment]
http://qinfo.clt.qq.com/cgi-bin/mem_card/set_group_mem_card

gc=&bkn=&name=&u=

Referer: http://qinfo.clt.qq.com/group_member_card/index.html?groupuin=&uin=&identity=2

Cookie: pt2gguin=; RK=jzV+bd8RRm; ptcz=956de15f70c64aad361a2e30ea025408a7ea2f94ff3496f0925a81710669c1ea; uin=; skey=ZovCPkIIO6

这段提示看看是否有帮助，昨天我在第一个框中看到了完整的群名片，这段协议搜自酷Q论坛

**Comment by waylonwang** [comment]
通过http://qun.qzone.qq.com/group#!/[groupuin]/member来爬取应该是最有效的方法，其中<a target="_blank" href="http://user.qzone.qq.com/[uin]" class=" member_name text_overflow">[完整的群名片昵称]</a>可以通过正则表达式来匹配并记录到数据表缓存中

**Comment by sjdy521** [comment]
群名片会被截断？这个以前都没有发觉到

**Comment by waylonwang** [comment]
因为一般的人群名片可能比较短，所以可能没有注意到

**Comment by waylonwang** [comment]
我跟踪了一下请求，找到了http://qun.qzone.qq.com/group#!/[groupuin]/member具体的获取群成员信息的接口是http://qun.qzone.qq.com/cgi-bin/get_group_member?uin=[用户QQ号]&groupid=[群号]&neednum=1&r=0.9828503488543949&g_tk=229651109，如果登录成功的话（应该是与web qq用得相同的cookie）可以返回：

**Comment by sjdy521** [comment]
现在就有拉取qun.qq.com的信息 只是我要从代码里确认下拉取到的card信息是否有用上

**Comment by waylonwang** [comment]
这个服务接口不是qun.qq.com的，是qun.qzone.qq.com的，不是一个域名的

**Comment by sjdy521** [comment]
@waylonwang 
已经参考 https://github.com/pandolia/qqbot/pull/109 换成了另外的api来获取群名片
相信该问题也已经得到了修复，再次感谢
