### ISSUE TITLE
发送消息重复

### ISSUE THREAD

**Issue by liangchenhe55** [sjdy521/Mojo-Webqq#98]
使用send_friend_message接口发送消息，请求一次会重复发送两遍至N遍不等，是怎么回事呢。

**Comment by sjdy521** [comment]
使用命令`cpanm Mojo::Webqq` 更新到最新版本即可解决

**Comment by liangchenhe55** [comment]
非常感谢回复。我已经更新了版本，当前：2.0.8，但是此问题依然存在。
腾讯云-CentOS7.2 x64 perl5.16.3

**Comment by sjdy521** [comment]
能否把运行过程中打印出来的日志贴出来看看

**Comment by liangchenhe55** [comment]
![qq 20170409204555](https://cloud.githubusercontent.com/assets/10266066/24837386/8aff429a-1d65-11e7-895a-3ddd9e9b3619.png)

如图所示，TestSend与TestSend2实际均只请求一次
